import json, os

NOTEBOOKS_DIR = os.path.dirname(os.path.abspath(__file__))

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 4,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.9.0",
                              "codemirror_mode": {"name": "ipython", "version": 3},
                              "file_extension": ".py", "mimetype": "text/x-python"}
        },
        "cells": cells
    }

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}


# ===========================================================================
# NOTEBOOK 02: Hartree-Fock Theory
# ===========================================================================

nb02_cells = [
    # Cell 1 - Title
    md(
        "# 02 — Hartree-Fock Theory\n\n"
        "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
        "(https://colab.research.google.com/github/ppt-2/Ch121a-DFT/blob/main/notebooks/02_hartree_fock.ipynb)"
    ),

    # Cell 2 - Learning Objectives
    md(
        "## 🎯 Learning Objectives\n\n"
        "By the end of this notebook, you will be able to:\n"
        "- Explain the Hartree-Fock approximation and Slater determinants\n"
        "- Perform HF calculations on simple molecules with PySCF\n"
        "- Monitor SCF convergence and understand the iterative procedure\n"
        "- Apply Koopmans' theorem to estimate ionization energies\n"
        "- Understand why HF fails for bond dissociation (static correlation)\n"
        "- Compare HF and MP2 results for H₂ dissociation"
    ),

    # Cell 3 - Theory
    md(
        r"## 1. Theory: Hartree-Fock Approximation"
        "\n\n"
        r"### 1.1 The Variational Principle and Slater Determinants"
        "\n\n"
        r"The exact many-electron wavefunction $\Psi(x_1, x_2, \ldots, x_N)$ is approximated"
        "\n"
        r"in HF as a single **Slater determinant** of one-electron spin-orbitals $\chi_i$:"
        "\n\n"
        r"$$\Psi_{HF} = \frac{1}{\sqrt{N!}} \begin{vmatrix} \chi_1(x_1) & \chi_2(x_1) & \cdots & \chi_N(x_1) \\ \chi_1(x_2) & \chi_2(x_2) & \cdots & \chi_N(x_2) \\ \vdots & \vdots & \ddots & \vdots \\ \chi_1(x_N) & \chi_2(x_N) & \cdots & \chi_N(x_N) \end{vmatrix}$$"
        "\n\n"
        r"The Slater determinant **automatically satisfies the Pauli antisymmetry principle**."
        "\n\n"
        r"### 1.2 The Fock Operator and HF Equations"
        "\n\n"
        r"Applying the variational principle to the Slater determinant yields the"
        "\n"
        r"**Hartree-Fock equations** (Roothan equations in the LCAO-MO basis):"
        "\n\n"
        r"$$\hat{F} |\phi_i\rangle = \epsilon_i |\phi_i\rangle$$"
        "\n\n"
        r"The Fock operator is:"
        "\n"
        r"$$\hat{F} = \hat{h} + \sum_j [2\hat{J}_j - \hat{K}_j]$$"
        "\n\n"
        r"where:"
        "\n"
        r"- $\hat{h}$ = one-electron (core) Hamiltonian (kinetic + nuclear attraction)"
        "\n"
        r"- $\hat{J}_j$ = Coulomb operator: $\hat{J}_j \phi_i(1) = \left[\int |\phi_j(2)|^2 r_{12}^{-1} d2\right] \phi_i(1)$"
        "\n"
        r"- $\hat{K}_j$ = Exchange operator: $\hat{K}_j \phi_i(1) = \left[\int \phi_j^*(2) \phi_i(2) r_{12}^{-1} d2\right] \phi_j(1)$"
        "\n\n"
        r"### 1.3 SCF Procedure"
        "\n\n"
        r"Because $\hat{F}$ depends on $\{\phi_i\}$, the equations are solved iteratively:"
        "\n\n"
        r"1. **Initial guess** for density matrix $\mathbf{P}$"
        "\n"
        r"2. **Build** Fock matrix $F_{\mu\nu} = H_{\mu\nu}^{core} + \sum_{\lambda\sigma} P_{\lambda\sigma} [(\mu\nu|\sigma\lambda) - \frac{1}{2}(\mu\lambda|\sigma\nu)]$"
        "\n"
        r"3. **Solve** $\mathbf{FC} = \mathbf{SC}\boldsymbol{\epsilon}$ (generalized eigenvalue problem)"
        "\n"
        r"4. **Update** density matrix $P_{\mu\nu} = 2\sum_{i}^{occ} C_{\mu i} C_{\nu i}$"
        "\n"
        r"5. **Check convergence** — repeat from step 2 if not converged"
        "\n\n"
        r"### 1.4 Koopmans' Theorem"
        "\n\n"
        r"The negative of the HF orbital energy approximates the ionization energy:"
        "\n"
        r"$$IE_i \approx -\epsilon_i$$"
        "\n\n"
        r"This is **Koopmans' theorem** — it assumes the other orbitals do not relax upon ionization"
        "\n"
        r"(the ""frozen orbital"" approximation). It is exact within HF but neglects orbital relaxation"
        "\n"
        r"and correlation effects."
        "\n\n"
        r"### 1.5 What HF misses: Electron Correlation"
        "\n\n"
        r"HF accounts for Coulomb repulsion only *on average* through the mean-field potential."
        "\n"
        r"It completely misses **electron correlation** — the instantaneous correlated motion"
        "\n"
        r"of electrons. The correlation energy is defined as:"
        "\n\n"
        r"$$E_{corr} = E_{exact} - E_{HF} < 0$$"
        "\n\n"
        r"**Static correlation** (near-degenerate configurations) and **dynamic correlation**"
        "\n"
        r"(short-range electron-electron cusps) both require post-HF methods."
    ),

    # Cell 4 - All imports + HF on multiple molecules
    code(
        "# =============================================================================\n"
        "# Ch121a: Quantum Chemistry & DFT — Notebook 02: Hartree-Fock Theory\n"
        "# License: GPL-3.0 (https://www.gnu.org/licenses/gpl-3.0.en.html)\n"
        "# =============================================================================\n"
        "import matplotlib\n"
        "matplotlib.rcParams['figure.dpi'] = 120\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from pyscf import gto, scf, mp\n"
        "\n"
        "# ------------------------------------------------------------------\n"
        "# HF/6-31G* calculations on small molecules\n"
        "# ------------------------------------------------------------------\n"
        "molecules = {\n"
        "    'H2O':  'O 0 0 0; H 0 0.757 -0.469; H 0 -0.757 -0.469',\n"
        "    'NH3':  'N 0 0 0.116; H 0 0.939 -0.269; H 0.814 -0.469 -0.269; H -0.814 -0.469 -0.269',\n"
        "    'CO':   'C 0 0 0; O 0 0 1.128',\n"
        "    'HF':   'H 0 0 0; F 0 0 0.917',\n"
        "}\n"
        "\n"
        "results = []\n"
        "for name, atom_str in molecules.items():\n"
        "    mol = gto.Mole()\n"
        "    mol.atom = atom_str\n"
        "    mol.basis = '6-31g*'\n"
        "    mol.verbose = 0\n"
        "    mol.build()\n"
        "    \n"
        "    mf = scf.RHF(mol)\n"
        "    mf.verbose = 0\n"
        "    e = mf.kernel()\n"
        "    \n"
        "    # Dipole moment\n"
        "    dm = mf.make_rdm1()\n"
        "    dip = mf.dip_moment(mol, dm, verbose=0)\n"
        "    dip_mag = np.linalg.norm(dip)\n"
        "    \n"
        "    # HOMO/LUMO\n"
        "    mo_e = mf.mo_energy\n"
        "    mo_occ = mf.mo_occ\n"
        "    homo_idx = np.where(mo_occ > 0)[0][-1]\n"
        "    lumo_idx = homo_idx + 1\n"
        "    homo_ev = mo_e[homo_idx] * 27.2114\n"
        "    lumo_ev = mo_e[lumo_idx] * 27.2114\n"
        "    gap_ev = lumo_ev - homo_ev\n"
        "    \n"
        "    results.append({\n"
        "        'Molecule': name,\n"
        "        'E_HF (Ha)': round(e, 6),\n"
        "        'Dipole (D)': round(dip_mag, 3),\n"
        "        'HOMO (eV)': round(homo_ev, 3),\n"
        "        'LUMO (eV)': round(lumo_ev, 3),\n"
        "        'Gap (eV)': round(gap_ev, 3),\n"
        "    })\n"
        "    print(f\"  {name:5s}  E = {e:.6f} Ha  μ = {dip_mag:.3f} D  HOMO = {homo_ev:.2f} eV\")\n"
        "\n"
        "df = pd.DataFrame(results)\n"
        "print(\"\\n\")\n"
        "print(\"HF/6-31G* Results:\")\n"
        "print(df.to_string(index=False))"
    ),

    # Cell 5 - SCF convergence monitoring
    code(
        "# ------------------------------------------------------------------\n"
        "# SCF Convergence Monitoring\n"
        "# ------------------------------------------------------------------\n"
        "# PySCF allows us to inject a callback function that is called\n"
        "# at the end of each SCF iteration.\n"
        "\n"
        "energies = []\n"
        "diis_errors = []\n"
        "\n"
        "def scf_callback(envs):\n"
        "    \"\"\"Called after each SCF iteration.\"\"\"\n"
        "    energies.append(envs['e_tot'])\n"
        "    if 'norm_gorb' in envs:\n"
        "        diis_errors.append(envs['norm_gorb'])\n"
        "\n"
        "mol = gto.Mole()\n"
        "mol.atom = 'O 0 0 0; H 0 0.757 -0.469; H 0 -0.757 -0.469'\n"
        "mol.basis = '6-31g*'\n"
        "mol.verbose = 0\n"
        "mol.build()\n"
        "\n"
        "mf = scf.RHF(mol)\n"
        "mf.verbose = 0\n"
        "mf.callback = scf_callback\n"
        "mf.kernel()\n"
        "\n"
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))\n"
        "\n"
        "iterations = list(range(1, len(energies) + 1))\n"
        "\n"
        "# Panel 1: Total energy vs iteration\n"
        "ax1.plot(iterations, energies, 'o-', color='steelblue', linewidth=2, markersize=8)\n"
        "ax1.axhline(y=energies[-1], color='coral', linestyle='--', alpha=0.7,\n"
        "            label=f'Converged: {energies[-1]:.8f} Ha')\n"
        "ax1.set_xlabel('SCF Iteration', fontsize=12)\n"
        "ax1.set_ylabel('Total HF Energy (Hartree)', fontsize=12)\n"
        "ax1.set_title('SCF Convergence: Total Energy\\nH₂O / 6-31G*', fontsize=12)\n"
        "ax1.legend(fontsize=9)\n"
        "ax1.grid(True, alpha=0.3)\n"
        "\n"
        "# Panel 2: Energy change per iteration (log scale)\n"
        "energy_changes = [abs(energies[i] - energies[i-1]) for i in range(1, len(energies))]\n"
        "ax2.semilogy(range(2, len(energies)+1), energy_changes, 's-',\n"
        "             color='seagreen', linewidth=2, markersize=8)\n"
        "ax2.axhline(y=1e-9, color='coral', linestyle='--', alpha=0.7, label='Convergence threshold')\n"
        "ax2.set_xlabel('SCF Iteration', fontsize=12)\n"
        "ax2.set_ylabel('|ΔE| (Hartree)', fontsize=12)\n"
        "ax2.set_title('SCF Convergence: Energy Change\\n(log scale)', fontsize=12)\n"
        "ax2.legend(fontsize=9)\n"
        "ax2.grid(True, alpha=0.3, which='both')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(f\"\\nConverged in {len(energies)} SCF iterations\")\n"
        "print(f\"Final energy: {energies[-1]:.10f} Ha\")"
    ),

    # Cell 6 - Koopmans' theorem
    code(
        "%%time\n"
        "# ------------------------------------------------------------------\n"
        "# Koopmans' Theorem: IE ≈ -ε_HOMO\n"
        "# ------------------------------------------------------------------\n"
        "# Compare predicted ionization energies (-HOMO energy) with experiment\n"
        "\n"
        "molecules_IE = {\n"
        "    'H2O':  ('O 0 0 0; H 0 0.757 -0.469; H 0 -0.757 -0.469', 12.62),\n"
        "    'NH3':  ('N 0 0 0.116; H 0 0.939 -0.269; H 0.814 -0.469 -0.269; H -0.814 -0.469 -0.269', 10.07),\n"
        "    'CO':   ('C 0 0 0; O 0 0 1.128', 14.01),\n"
        "    'HF':   ('H 0 0 0; F 0 0 0.917', 16.03),\n"
        "    'N2':   ('N 0 0 0; N 0 0 1.098', 15.58),\n"
        "}\n"
        "\n"
        "koopman_results = []\n"
        "for name, (atom_str, exp_ie) in molecules_IE.items():\n"
        "    mol = gto.Mole()\n"
        "    mol.atom = atom_str\n"
        "    mol.basis = '6-31g*'\n"
        "    mol.verbose = 0\n"
        "    mol.build()\n"
        "    \n"
        "    mf = scf.RHF(mol)\n"
        "    mf.verbose = 0\n"
        "    mf.kernel()\n"
        "    \n"
        "    mo_e = mf.mo_energy\n"
        "    mo_occ = mf.mo_occ\n"
        "    homo_idx = np.where(mo_occ > 0)[0][-1]\n"
        "    comp_ie = -mo_e[homo_idx] * 27.2114\n"
        "    \n"
        "    koopman_results.append({\n"
        "        'Molecule': name,\n"
        "        'Computed IE (eV)': round(comp_ie, 2),\n"
        "        'Experimental IE (eV)': exp_ie,\n"
        "        'Error (eV)': round(comp_ie - exp_ie, 2),\n"
        "    })\n"
        "\n"
        "df_k = pd.DataFrame(koopman_results)\n"
        "print(\"Koopmans' Theorem: HF/6-31G* Ionization Energies\")\n"
        "print(df_k.to_string(index=False))\n"
        "\n"
        "mae = np.mean(np.abs(df_k['Error (eV)']))\n"
        "print(f\"\\nMean Absolute Error: {mae:.2f} eV\")\n"
        "\n"
        "# Plot\n"
        "fig, ax = plt.subplots(figsize=(7, 5))\n"
        "x = np.array(df_k['Experimental IE (eV)'])\n"
        "y = np.array(df_k['Computed IE (eV)'])\n"
        "names = list(df_k['Molecule'])\n"
        "\n"
        "colors_mol = ['steelblue', 'coral', 'seagreen', 'mediumpurple', '#E67E22']\n"
        "for xi, yi, name, col in zip(x, y, names, colors_mol):\n"
        "    ax.scatter(xi, yi, color=col, s=120, zorder=5, label=name)\n"
        "\n"
        "# y=x line (perfect agreement)\n"
        "lim_min = min(min(x), min(y)) - 0.5\n"
        "lim_max = max(max(x), max(y)) + 0.5\n"
        "ax.plot([lim_min, lim_max], [lim_min, lim_max], 'k--', alpha=0.4, label='Perfect agreement')\n"
        "\n"
        "ax.set_xlabel('Experimental IE (eV)', fontsize=12)\n"
        "ax.set_ylabel('Computed IE / Koopmans (eV)', fontsize=12)\n"
        "ax.set_title(\"Koopmans' Theorem vs Experiment\\nHF/6-31G*\", fontsize=12)\n"
        "ax.legend(fontsize=9)\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),

    # Cell 7 - H2 bond dissociation
    code(
        "%%time\n"
        "# ------------------------------------------------------------------\n"
        "# H₂ Bond Dissociation: RHF vs MP2\n"
        "# ------------------------------------------------------------------\n"
        "# RHF fails at dissociation because it forces double occupation,\n"
        "# giving incorrect ionic character (H⁺ + H⁻) at long range.\n"
        "# MP2 partially corrects this via perturbation theory.\n"
        "\n"
        "from pyscf import gto, scf, mp\n"
        "\n"
        "distances = np.linspace(0.5, 4.0, 30)   # Angstroms\n"
        "e_rhf = []\n"
        "e_mp2 = []\n"
        "\n"
        "for d in distances:\n"
        "    mol = gto.Mole()\n"
        "    mol.atom = f'H 0 0 0; H 0 0 {d}'\n"
        "    mol.basis = 'cc-pVDZ'\n"
        "    mol.verbose = 0\n"
        "    mol.build()\n"
        "    \n"
        "    mf = scf.RHF(mol)\n"
        "    mf.verbose = 0\n"
        "    ehf = mf.kernel()\n"
        "    e_rhf.append(ehf)\n"
        "    \n"
        "    # MP2 on top of RHF\n"
        "    mpt = mp.MP2(mf)\n"
        "    mpt.verbose = 0\n"
        "    emp2, _ = mpt.kernel()\n"
        "    e_mp2.append(ehf + emp2)\n"
        "\n"
        "e_rhf = np.array(e_rhf)\n"
        "e_mp2 = np.array(e_mp2)\n"
        "\n"
        "# Normalize to equilibrium minimum\n"
        "e_rhf_norm = (e_rhf - e_rhf.min()) * 627.509   # kcal/mol\n"
        "e_mp2_norm = (e_mp2 - e_mp2.min()) * 627.509\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 5))\n"
        "ax.plot(distances, e_rhf_norm, 'o-', color='coral', linewidth=2,\n"
        "        markersize=4, label='RHF/cc-pVDZ')\n"
        "ax.plot(distances, e_mp2_norm, 's-', color='steelblue', linewidth=2,\n"
        "        markersize=4, label='MP2/cc-pVDZ')\n"
        "\n"
        "# Reference: exact 2H dissociation limit\n"
        "# 2 * E(H atom, UHF) at large distance\n"
        "ax.axhline(y=0, color='gray', linestyle=':', alpha=0.5)\n"
        "\n"
        "ax.set_xlabel('H-H Distance (Å)', fontsize=12)\n"
        "ax.set_ylabel('Relative Energy (kcal/mol)', fontsize=12)\n"
        "ax.set_title('H₂ Bond Dissociation: RHF vs MP2\\n(cc-pVDZ)', fontsize=12)\n"
        "ax.legend(fontsize=11)\n"
        "ax.grid(True, alpha=0.3)\n"
        "ax.set_xlim(0.4, 4.1)\n"
        "ax.set_ylim(-5, 80)\n"
        "\n"
        "# Annotate RHF error\n"
        "ax.annotate('RHF unphysically\\nraises at dissociation\\n(static correlation error)',\n"
        "            xy=(3.5, e_rhf_norm[-3]), xytext=(2.5, 50),\n"
        "            arrowprops=dict(arrowstyle='->', color='coral'),\n"
        "            fontsize=9, color='coral')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print(\"\\nKey insight:\")\n"
        "print(\"  RHF forces the wavefunction to be a single Slater determinant,\")\n"
        "print(\"  which cannot properly describe bond breaking.\")\n"
        "print(\"  At large r(H-H), the true wavefunction should be:\")\n"
        "print(\"    Ψ ∝ |H↑ H↓⟩ - |H↓ H↑⟩  (purely covalent)\")\n"
        "print(\"  But RHF gives equal weight to ionic H⁺H⁻ configurations.\")"
    ),

    # Cell 8 - Research Connection
    md(
        "## 🔬 Research Connection\n\n"
        "Hartree-Fock theory, despite its limitations, remains fundamental:\n\n"
        "- **Starting point for coupled cluster**: CCSD(T), the \"gold standard\" of quantum chemistry,\n"
        "  builds on HF via perturbation theory and cluster operators.\n"
        "- **HF in DFT**: The Kohn-Sham equations have the same structure as HF, but replace\n"
        "  the exact exchange with an approximate exchange-correlation functional.\n"
        "- **Orbital analysis**: HF molecular orbitals (sigma, pi, lone pairs) provide chemical\n"
        "  intuition used daily in organic and organometallic chemistry.\n"
        "- **Limitations drive innovation**: The failures of HF (correlation energy, dispersion,\n"
        "  open-shell systems) motivated the entire field of post-HF and DFT methods.\n\n"
        "**Notable paper:** Roothaan, C.C.J. (1951). *Rev. Mod. Phys.* **23**, 69 — derived\n"
        "the matrix HF equations (Roothaan equations) that all modern QC codes implement."
    ),

    # Cell 9 - Summary
    md(
        "## 📋 Summary\n\n"
        "| Concept | Key Result |\n"
        "|---------|----------|\n"
        "| Slater determinant | Antisymmetric wavefunction for N fermions; incorporates Pauli principle |\n"
        r"| Fock operator | $\hat{F} = \hat{h} + \hat{J} - \hat{K}$; mean-field treatment of e-e repulsion |"
        "\n"
        "| SCF procedure | Iterative diagonalization until density matrix converges |\n"
        r"| Koopmans' theorem | $\text{IE} \approx -\epsilon_{HOMO}$; error ~0.5-1.5 eV for typical molecules |"
        "\n"
        r"| HF correlation energy | $E_{corr} = E_{exact} - E_{HF} \approx$ -0.5 to -1.5 eV/electron pair |"
        "\n"
        "| H₂ dissociation | RHF fails; needs multi-reference methods or UHF |\n\n"
        "**Post-HF hierarchy** (increasing accuracy, increasing cost):\n"
        "HF → MP2 → CCSD → CCSD(T) → FCI\n\n"
        "**DFT alternative** (similar cost to HF, better accuracy):\n"
        r"DFT captures ~80-90% of correlation energy implicitly through $E_{xc}$"
    ),

    # Cell 10 - Exercises
    md(
        "## 📝 Exercises\n\n"
        "1. **Basis set effect on Koopmans'**: Redo the Koopmans' theorem calculation using\n"
        "   `def2-TZVP` instead of `6-31G*`. Does a larger basis set improve agreement with\n"
        "   experiment? Why or why not?\n\n"
        "2. **SCF starting point**: Try using `mf.init_guess = 'atom'` vs `mf.init_guess = 'huckel'`\n"
        "   for the water SCF calculation. Does the starting guess affect the converged energy?\n"
        "   Does it affect the number of iterations?\n\n"
        "3. **Open-shell HF**: CO has a singlet ground state. Run UHF (unrestricted HF) on \n"
        "   the triplet state of CO using `mol.spin = 2` and `scf.UHF(mol)`.\n"
        "   What is the energy difference between singlet and triplet?\n\n"
        "4. **HOMO-LUMO gap trends**: Compute HF/6-31G* HOMO-LUMO gaps for \n"
        "   ethylene (C₂H₄), butadiene (C₄H₆), hexatriene (C₆H₈), and benzene (C₆H₆).\n"
        "   Plot gap vs number of double bonds. What trend do you observe?\n\n"
        "5. **Correlation energy estimate**: Compute RHF and MP2 energies for H₂O with cc-pVTZ.\n"
        "   What fraction of the correlation energy does MP2 recover (compared to ~-0.37 Ha\n"
        "   for the experimental correlation energy of water)?"
    ),
]


# ===========================================================================
# NOTEBOOK 03: DFT Fundamentals
# ===========================================================================

nb03_cells = [
    # Cell 1 - Title
    md(
        "# 03 — DFT Fundamentals: From Hohenberg-Kohn to Modern Functionals\n\n"
        "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
        "(https://colab.research.google.com/github/ppt-2/Ch121a-DFT/blob/main/notebooks/03_dft_fundamentals.ipynb)"
    ),

    # Cell 2 - Learning Objectives
    md(
        "## 🎯 Learning Objectives\n\n"
        "By the end of this notebook, you will be able to:\n"
        "- State and explain the two Hohenberg-Kohn theorems\n"
        "- Describe the Kohn-Sham DFT formalism and its connection to HF\n"
        "- Classify exchange-correlation functionals on Jacob's Ladder\n"
        "- Compare LDA, GGA, meta-GGA, hybrid, and double-hybrid functionals\n"
        "- Understand dispersion corrections (DFT-D3, D4)\n"
        "- Choose an appropriate functional for a given chemical problem"
    ),

    # Cell 3 - Theory
    md(
        r"## 1. Theory: From Density to Energy"
        "\n\n"
        r"### 1.1 Hohenberg-Kohn Theorems (1964)"
        "\n\n"
        r"DFT is built on two exact theorems by Hohenberg and Kohn:"
        "\n\n"
        r"**Theorem 1 (Existence):** The external potential $v_{ext}(\mathbf{r})$ — and hence the"
        "\n"
        r"total energy — is a unique functional of the ground-state electron density $n_0(\mathbf{r})$:"
        "\n\n"
        r"$$E = E[n_0]$$"
        "\n\n"
        r"**Theorem 2 (Variational principle):** The universal functional $F[n]$ delivers"
        "\n"
        r"the ground-state energy if and only if the true ground-state density is used:"
        "\n\n"
        r"$$E[n] \geq E_0 \quad \text{for all } n \neq n_0$$"
        "\n\n"
        r"These theorems establish that $n(\mathbf{r})$ — a function of only 3 spatial variables"
        "\n"
        r"— contains all information needed to determine the ground-state energy."
        "\n\n"
        r"### 1.2 Kohn-Sham DFT (1965)"
        "\n\n"
        r"The practical implementation by Kohn and Sham introduces a fictitious non-interacting"
        "\n"
        r"reference system with the **same density** as the real interacting system."
        "\n\n"
        r"The Kohn-Sham equations are:"
        "\n\n"
        r"$$\left[-\frac{1}{2}\nabla^2 + v_{eff}(\mathbf{r})\right]\phi_i(\mathbf{r}) = \epsilon_i \phi_i(\mathbf{r})$$"
        "\n\n"
        r"where the effective potential is:"
        "\n\n"
        r"$$v_{eff}(\mathbf{r}) = v_{ext}(\mathbf{r}) + \underbrace{\int \frac{n(\mathbf{r}')}{|\mathbf{r}-\mathbf{r}'|} d\mathbf{r}'}_{v_{Hartree}} + \underbrace{v_{xc}[n](\mathbf{r})}_{exchange-correlation}$$"
        "\n\n"
        r"The total DFT energy is:"
        "\n\n"
        r"$$E_{KS}[n] = T_s[n] + E_{ne}[n] + J[n] + E_{xc}[n]$$"
        "\n\n"
        r"where $T_s$ = kinetic energy of non-interacting electrons, $E_{ne}$ = nuclear-electron"
        "\n"
        r"attraction, $J$ = classical Coulomb (Hartree) energy, and $E_{xc}$ = exchange-correlation energy."
        "\n\n"
        r"### 1.3 The Exchange-Correlation Functional"
        "\n\n"
        r"The exact $E_{xc}[n]$ is unknown. All DFT methods differ in how they approximate it."
        "\n\n"
        r"$$E_{xc}[n] = E_x[n] + E_c[n]$$"
        "\n\n"
        r"**Exchange energy** $E_x$ accounts for the Fermi hole (Pauli antisymmetry),"
        "\n"
        r"**correlation energy** $E_c$ captures dynamic and static electron correlation."
        "\n\n"
        r"### 1.4 Dispersion Interactions"
        "\n\n"
        r"Standard DFT functionals miss long-range London dispersion ($r^{-6}$ decay)."
        "\n"
        r"The DFT-D3 correction by Grimme adds:"
        "\n\n"
        r"$$E_{DFT-D3} = -\frac{1}{2}\sum_{i\neq j} s_6 \frac{C_6^{ij}}{r_{ij}^6} f_{damp}(r_{ij}) + s_8 \frac{C_8^{ij}}{r_{ij}^8} f_{damp}(r_{ij})$$"
        "\n\n"
        r"Use keywords in ORCA: `B3LYP-D3BJ/def2-SVP` or `PBE0-D3/def2-TZVP`"
    ),

    # Cell 4 - Imports + Jacob's Ladder diagram
    code(
        "# =============================================================================\n"
        "# Ch121a: Quantum Chemistry & DFT — Notebook 03: DFT Fundamentals\n"
        "# License: GPL-3.0 (https://www.gnu.org/licenses/gpl-3.0.en.html)\n"
        "# =============================================================================\n"
        "import matplotlib\n"
        "matplotlib.rcParams['figure.dpi'] = 120\n"
        "import matplotlib.pyplot as plt\n"
        "import matplotlib.patches as mpatches\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from pyscf import gto, dft, scf\n"
        "\n"
        "# ------------------------------------------------------------------\n"
        "# Jacob's Ladder of DFT Approximations\n"
        "# ------------------------------------------------------------------\n"
        "fig, ax = plt.subplots(figsize=(11, 8))\n"
        "ax.set_xlim(0, 10)\n"
        "ax.set_ylim(0, 11)\n"
        "ax.axis('off')\n"
        "\n"
        "# Color gradient from bottom (warm) to top (cool)\n"
        "rung_colors = ['#F9A825', '#FB8C00', '#E64A19', '#8E24AA', '#1565C0']\n"
        "rung_data = [\n"
        "    (1, 'Rung 1: LDA',      'Local Density\\nApproximation',\n"
        "     'PW92, VWN, SVWN',      r'$n(\\mathbf{r})$'),\n"
        "    (2, 'Rung 2: GGA',       'Generalized Gradient\\nApproximation',\n"
        "     'PBE, BLYP, BP86',       r'$n, \\nabla n$'),\n"
        "    (3, 'Rung 3: meta-GGA',  'Kinetic Energy Density',\n"
        "     'TPSS, M06-L, SCAN',     r'$n, \\nabla n, \\tau$'),\n"
        "    (4, 'Rung 4: Hybrid',    'Exact HF Exchange\\n(partial)',\n"
        "     'B3LYP, PBE0, M06',      r'$n, \\nabla n, E_x^{HF}$'),\n"
        "    (5, 'Rung 5: Dbl Hybrid','HF Exchange + MP2\\nCorrelation',\n"
        "     r'$\\omega$B97X-D, B2-PLYP',r'$n, \\nabla n, E_x^{HF}, E_c^{MP2}$'),\n"
        "]\n"
        "\n"
        "# Draw ladder poles\n"
        "ax.plot([1.5, 1.5], [0.3, 10.2], 'k-', lw=3, zorder=1)\n"
        "ax.plot([8.5, 8.5], [0.3, 10.2], 'k-', lw=3, zorder=1)\n"
        "\n"
        "for (rung_num, title, subtitle, functionals, ingredients) in rung_data:\n"
        "    y_center = rung_num * 1.75 - 0.8\n"
        "    color = rung_colors[rung_num - 1]\n"
        "    \n"
        "    # Rung (horizontal bar)\n"
        "    rung_patch = mpatches.FancyBboxPatch((1.6, y_center - 0.5), 6.8, 1.0,\n"
        "                                          boxstyle=\"round,pad=0.05\",\n"
        "                                          facecolor=color, edgecolor='white',\n"
        "                                          linewidth=2, alpha=0.88, zorder=2)\n"
        "    ax.add_patch(rung_patch)\n"
        "    \n"
        "    # Title text\n"
        "    ax.text(5.0, y_center + 0.15, title, ha='center', va='center',\n"
        "            fontsize=11, fontweight='bold', color='white', zorder=3)\n"
        "    \n"
        "    # Functional examples (left)\n"
        "    ax.text(2.2, y_center - 0.22, functionals, ha='left', va='center',\n"
        "            fontsize=8.5, color='white', zorder=3, style='italic')\n"
        "    \n"
        "    # Ingredients (right)\n"
        "    ax.text(7.8, y_center, ingredients, ha='right', va='center',\n"
        "            fontsize=8.5, color='white', zorder=3)\n"
        "\n"
        "# 'Chemical Accuracy' bar at top\n"
        "ca_patch = mpatches.FancyBboxPatch((1.0, 9.2), 8.0, 0.8,\n"
        "                                    boxstyle=\"round,pad=0.1\",\n"
        "                                    facecolor='#2ECC71', edgecolor='gold',\n"
        "                                    linewidth=3, alpha=0.9, zorder=2)\n"
        "ax.add_patch(ca_patch)\n"
        "ax.text(5.0, 9.62, '🎯 Chemical Accuracy: < 1 kcal/mol',\n"
        "        ha='center', va='center', fontsize=12, fontweight='bold',\n"
        "        color='white', zorder=3)\n"
        "\n"
        "# 'Heaven' / exact label\n"
        "ax.text(5.0, 10.6, '☁  Heaven: Exact Exchange-Correlation',\n"
        "        ha='center', va='center', fontsize=10, color='gray', style='italic')\n"
        "\n"
        "# Ground label\n"
        "ax.text(5.0, 0.1, '⚡ Hartree World (no XC)',\n"
        "        ha='center', va='center', fontsize=9.5, color='#7F8C8D')\n"
        "\n"
        "# Title\n"
        "ax.set_title(\"Jacob's Ladder of Density Functional Approximations\",\n"
        "             fontsize=14, fontweight='bold', pad=10)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),

    # Cell 5 - Functional comparison on H2O
    code(
        "%%time\n"
        "# ------------------------------------------------------------------\n"
        "# DFT Functional Comparison on H₂O / def2-SVP\n"
        "# ------------------------------------------------------------------\n"
        "\n"
        "mol = gto.Mole()\n"
        "mol.atom = '''O  0.000000  0.000000  0.117176\n"
        "H  0.000000  0.757001 -0.468704\n"
        "H  0.000000 -0.757001 -0.468704'''\n"
        "mol.basis = 'def2-SVP'\n"
        "mol.verbose = 0\n"
        "mol.build()\n"
        "\n"
        "functionals = {\n"
        "    'SVWN':  ('LDA',       '#F9A825'),\n"
        "    'PBE':   ('GGA',       '#FB8C00'),\n"
        "    'TPSS':  ('meta-GGA',  '#E64A19'),\n"
        "    'B3LYP': ('Hybrid',    '#8E24AA'),\n"
        "    'PBE0':  ('Hybrid',    '#1565C0'),\n"
        "}\n"
        "\n"
        "results = []\n"
        "for func, (category, color) in functionals.items():\n"
        "    mf = dft.RKS(mol)\n"
        "    mf.xc = func\n"
        "    mf.verbose = 0\n"
        "    e = mf.kernel()\n"
        "    dm = mf.make_rdm1()\n"
        "    dip = mf.dip_moment(mol, dm, verbose=0)\n"
        "    dip_mag = np.linalg.norm(dip)\n"
        "    results.append({\n"
        "        'Functional': func, 'Category': category,\n"
        "        'Energy (Ha)': round(e, 6), 'Dipole (D)': round(dip_mag, 3),\n"
        "        'Color': color\n"
        "    })\n"
        "    print(f\"  {func:8s} ({category:10s}): E = {e:.6f} Ha  μ = {dip_mag:.3f} D\")\n"
        "\n"
        "df = pd.DataFrame(results)\n"
        "print(\"\\n\")\n"
        "print(df[['Functional','Category','Energy (Ha)','Dipole (D)']].to_string(index=False))\n"
        "\n"
        "# Plot\n"
        "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))\n"
        "\n"
        "# Panel 1: Total energies\n"
        "energies = df['Energy (Ha)'].values\n"
        "funcs = df['Functional'].values\n"
        "colors_list = df['Color'].values\n"
        "\n"
        "bars1 = ax1.bar(funcs, energies - energies.max(), color=colors_list,\n"
        "                edgecolor='white', linewidth=0.5)\n"
        "ax1.set_xlabel('DFT Functional', fontsize=12)\n"
        "ax1.set_ylabel('ΔE relative to SVWN (Ha)', fontsize=11)\n"
        "ax1.set_title('DFT Functional Comparison: H₂O\\ndef2-SVP basis', fontsize=12)\n"
        "ax1.grid(True, alpha=0.3, axis='y')\n"
        "for bar, e in zip(bars1, energies):\n"
        "    ax1.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.0005,\n"
        "             f'{e:.4f}', ha='center', va='bottom', fontsize=8, rotation=30)\n"
        "\n"
        "# Panel 2: Dipole moments\n"
        "dipoles = df['Dipole (D)'].values\n"
        "bars2 = ax2.bar(funcs, dipoles, color=colors_list, edgecolor='white', linewidth=0.5)\n"
        "ax2.axhline(y=1.85, color='black', linestyle='--', alpha=0.7, label='Experiment (1.85 D)')\n"
        "ax2.set_xlabel('DFT Functional', fontsize=12)\n"
        "ax2.set_ylabel('Dipole Moment (Debye)', fontsize=12)\n"
        "ax2.set_title('Dipole Moments: H₂O / def2-SVP', fontsize=12)\n"
        "ax2.legend(fontsize=9)\n"
        "ax2.grid(True, alpha=0.3, axis='y')\n"
        "for bar, d in zip(bars2, dipoles):\n"
        "    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,\n"
        "             f'{d:.3f}', ha='center', va='bottom', fontsize=9)\n"
        "\n"
        "# Add category labels\n"
        "from matplotlib.patches import Patch\n"
        "legend_elements = [\n"
        "    Patch(facecolor='#F9A825', label='LDA'),\n"
        "    Patch(facecolor='#FB8C00', label='GGA'),\n"
        "    Patch(facecolor='#E64A19', label='meta-GGA'),\n"
        "    Patch(facecolor='#8E24AA', label='Hybrid'),\n"
        "    Patch(facecolor='#1565C0', label='Hybrid'),\n"
        "]\n"
        "ax1.legend(handles=legend_elements[:3], fontsize=8, title='Rung')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ),

    # Cell 6 - Dispersion correction concept
    code(
        "# ------------------------------------------------------------------\n"
        "# DFT-D3 Dispersion Correction\n"
        "# ------------------------------------------------------------------\n"
        "# Standard DFT functionals miss van der Waals / London dispersion\n"
        "# interactions. Grimme's DFT-D3 correction adds pairwise C6/r^6 terms.\n"
        "\n"
        "import numpy as np\n"
        "import matplotlib\n"
        "matplotlib.rcParams['figure.dpi'] = 120\n"
        "import matplotlib.pyplot as plt\n"
        "\n"
        "# Conceptual: Lennard-Jones-like comparison\n"
        "r = np.linspace(2.5, 12, 500)   # Angstrom\n"
        "\n"
        "# Approximate DFT (no dispersion) for benzene dimer: flat near repulsion, no well\n"
        "def dft_nodispersion(r):\n"
        "    # Simplified: Pauli repulsion only, very shallow\n"
        "    return 5.0 * np.exp(-r/1.5) - 0.2 * np.exp(-r/4.0)\n"
        "\n"
        "# With D3 correction: adds -C6/r^6 term\n"
        "def dft_d3(r, C6=45.0, s6=1.0):\n"
        "    return dft_nodispersion(r) - s6 * C6 / r**6\n"
        "\n"
        "E_nodis = dft_nodispersion(r)\n"
        "E_d3 = dft_d3(r)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 5))\n"
        "ax.plot(r, E_nodis, '--', color='coral', linewidth=2.5, label='DFT (no dispersion)')\n"
        "ax.plot(r, E_d3, '-', color='steelblue', linewidth=2.5, label='DFT-D3')\n"
        "ax.axhline(y=0, color='gray', linewidth=0.8, linestyle=':', alpha=0.7)\n"
        "ax.fill_between(r, E_d3, 0, where=(E_d3 < 0), alpha=0.15, color='steelblue',\n"
        "                label='Dispersion well')\n"
        "ax.set_xlim(2.5, 12)\n"
        "ax.set_ylim(-0.6, 1.0)\n"
        "ax.set_xlabel('Intermolecular Distance (Å)', fontsize=12)\n"
        "ax.set_ylabel('Interaction Energy (kcal/mol)', fontsize=12)\n"
        "ax.set_title('Effect of DFT-D3 Dispersion Correction\\n(Conceptual: benzene dimer)', fontsize=12)\n"
        "ax.legend(fontsize=10)\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print(\"DFT-D3 Dispersion Correction Summary:\")\n"
        "print(\"  ΔE_disp = -Σ_{i<j} s₆ C₆ᵢʲ/r₆ + s₈ C₈ᵢʲ/r₈  (with damping function)\")\n"
        "print()\n"
        "print(\"Usage in PySCF:\")\n"
        "print(\"  mf = dft.RKS(mol)\")\n"
        "print(\"  mf.xc = 'B3LYP'\")\n"
        "print(\"  from pyscf import dftd3  # requires dftd3 Python bindings\")\n"
        "print(\"  mf = dftd3.dftd3(mf)    # wraps mf with D3 correction\")\n"
        "print()\n"
        "print(\"Usage in ORCA:\")\n"
        "print(\"  ! B3LYP-D3BJ def2-SVP Opt\")\n"
        "print(\"  ! PBE0-D3/def2-TZVP Energy\")\n"
        "print()\n"
        "print(\"Common dispersion variants:\")\n"
        "print(\"  -D3(BJ): Becke-Johnson damping (recommended for most systems)\")\n"
        "print(\"  -D3(0):  Zero-damping (Grimme 2010, original)\")\n"
        "print(\"  -D4:     Charge-dependent, more accurate for ionic systems\")"
    ),

    # Cell 7 - Functional table
    md(
        "## 2. DFT Functional Reference Table\n\n"
        "| Functional | Type | %HF Exchange | Dispersion | Cost | Accuracy | Good For | Caution |\n"
        "|------------|------|:---:|:---:|:---:|:---:|---------|----------|\n"
        "| SVWN | LDA | 0 | ✗ | ★ | ★★ | Solids, quick tests | Overbinds molecules |\n"
        "| PBE | GGA | 0 | ✗ | ★★ | ★★★ | Solids, surfaces | Self-interaction |\n"
        "| BLYP | GGA | 0 | ✗ | ★★ | ★★★ | Organics | Dispersion missing |\n"
        "| TPSS | meta-GGA | 0 | ✗ | ★★★ | ★★★ | General chemistry | Slow |\n"
        "| M06-L | meta-GGA | 0 | ✗ | ★★★ | ★★★★ | Transition metals | Sensitive to grid |\n"
        "| B3LYP | Hybrid | 20 | ✗ | ★★★ | ★★★★ | Organics, pharmacy | No dispersion; fails TM |\n"
        "| B3LYP-D3 | Hybrid+D | 20 | ✓ | ★★★ | ★★★★ | General organics | TM still tricky |\n"
        "| PBE0 | Hybrid | 25 | ✗ | ★★★ | ★★★★ | General chemistry | Dispersion missing |\n"
        "| PBE0-D3 | Hybrid+D | 25 | ✓ | ★★★ | ★★★★★ | **Recommended general** | |\n"
        "| TPSSh | Hybrid | 10 | ✗ | ★★★ | ★★★★ | Transition metals | |\n"
        "| M06 | Hybrid | 27 | ✗ | ★★★★ | ★★★★ | Main group + TM | Sensitive to grid |\n"
        "| M06-2X | Hybrid | 54 | ✗ | ★★★★ | ★★★★★ | Thermochem, kinetics | Fails for TM |\n"
        "| ωB97X-D | Range-sep | var | ✓ | ★★★★ | ★★★★★ | CT excitations, NCI | Expensive |\n"
        "| CAM-B3LYP | Range-sep | var | ✗ | ★★★★ | ★★★★ | CT, long-range | |\n"
        "| B2-PLYP | Double hybrid | 53 | ✗ | ★★★★★ | ★★★★★ | High accuracy | Very expensive |\n\n"
        "**Course recommendations:**\n"
        "- **Geometry optimization**: `B3LYP/def2-SVP` or `PBE0/def2-SVP`\n"
        "- **Energies**: `PBE0-D3/def2-TZVP` or `B3LYP-D3BJ/def2-TZVP`\n"
        "- **Transition metals**: `TPSSh/def2-SVP` or `M06/def2-SVP`\n"
        "- **Excited states**: `CAM-B3LYP/def2-SVP` (TD-DFT)"
    ),

    # Cell 8 - Research Connection
    md(
        "## 🔬 Research Connection\n\n"
        "DFT is the workhorse of modern computational chemistry and materials science:\n\n"
        "- **~50% of all computational chemistry papers** use DFT (B3LYP alone has >100,000 citations)\n"
        "- **Drug design**: DFT computes binding site interactions, reaction mechanisms in metalloenzymes\n"
        "- **Heterogeneous catalysis**: PBE/plane-waves for surface reactions (e.g., CO₂ reduction)\n"
        "- **Battery materials**: DFT predicts lithium intercalation energies in electrode materials\n"
        "- **Nobel Prizes**: Kohn (1998 Chemistry), Karplus/Levitt/Warshel (2013 Chemistry)\n\n"
        "**The DFT accuracy crisis**: B3LYP was found to fail for dispersion-dominated systems,\n"
        "kinetics (reaction barriers), and transition metal complexes. This drove development\n"
        "of M06-2X, ωB97X-D, and dispersion corrections, now standard in publications.\n\n"
        "**Key reference:** Becke, A.D. (1993). *J. Chem. Phys.* **98**, 5648 — the B3LYP paper,\n"
        "one of the most cited scientific papers of all time (~90,000 citations)."
    ),

    # Cell 9 - Summary
    md(
        "## 📋 Summary\n\n"
        "| Concept | Key Points |\n"
        "|---------|----------|\n"
        r"| HK Theorem 1 | Ground state energy is a unique functional of $n_0(\mathbf{r})$ |"
        "\n"
        r"| HK Theorem 2 | Variational principle: true $n_0$ minimizes $E[n]$ |"
        "\n"
        "| Kohn-Sham DFT | Non-interacting reference with same density; same structure as HF |\n"
        r"| LDA | Uses only $n(\mathbf{r})$; overbinds; good for solids |"
        "\n"
        r"| GGA | Adds $\nabla n$; better for molecules; missing dispersion |"
        "\n"
        "| Hybrid | Mixes HF exchange; best for most molecular applications |\n"
        r"| Dispersion | -D3(BJ) adds $C_6/r^6$ correction; always use for weak interactions |"
        "\n\n"
        "**When DFT works well:** Geometries (±0.01-0.02 Å), reaction energies (±2 kcal/mol),\n"
        "vibrational frequencies, dipole moments, NMR shifts\n\n"
        "**When DFT struggles:** Strong correlation (multi-reference), charge-transfer excitations (without range-separation), dispersion (without correction), delocalization error"
    ),

    # Cell 10 - Exercises
    md(
        "## 📝 Exercises\n\n"
        "1. **Jacob's Ladder**: For each rung (LDA, GGA, meta-GGA, hybrid), name one functional\n"
        "   not listed in the notebook. Look up its year of publication and the journal it appeared in.\n\n"
        "2. **Functional comparison**: Run the water functional comparison with `aug-cc-pVTZ`\n"
        "   instead of `def2-SVP`. Does the ordering of energies change? Why might it?\n\n"
        "3. **Dispersion in benzene dimer**: Using PySCF, compute the interaction energy of\n"
        "   two benzene molecules (face-to-face at 3.8 Å) with B3LYP/6-31G* (no dispersion).\n"
        "   What sign is the interaction? Is this physical?\n\n"
        "4. **Exact exchange fraction**: B3LYP uses 20% HF exchange. Try changing this using\n"
        "   `mf.xc = '0.15*HF + 0.85*B88, LYP'` and `mf.xc = '0.30*HF + 0.70*B88, LYP'`.\n"
        "   How do the energy and dipole moment of water change?\n\n"
        "5. **DFT vs HF correlation energy**: Compare the energy of H₂O computed by\n"
        "   RHF/def2-SVP and PBE/def2-SVP. The difference approximates how much correlation\n"
        "   energy DFT captures. How does this compare to the MP2 correlation energy?"
    ),
]


# ===========================================================================
# Write notebooks
# ===========================================================================

path_02 = os.path.join(NOTEBOOKS_DIR, '02_hartree_fock.ipynb')
path_03 = os.path.join(NOTEBOOKS_DIR, '03_dft_fundamentals.ipynb')

with open(path_02, 'w', encoding='utf-8') as f:
    json.dump(nb(nb02_cells), f, indent=1, ensure_ascii=False)

with open(path_03, 'w', encoding='utf-8') as f:
    json.dump(nb(nb03_cells), f, indent=1, ensure_ascii=False)

# Verify
for path in [path_02, path_03]:
    size = os.path.getsize(path)
    print(f"{os.path.basename(path)}: {size:,} bytes")
    # Quick validity check
    with open(path) as f:
        data = json.load(f)
    assert data['nbformat'] == 4
    assert data['nbformat_minor'] == 4
    assert len(data['cells']) == 10
    print(f"  -> nbformat {data['nbformat']}.{data['nbformat_minor']}, {len(data['cells'])} cells ✓")
