import json, os

NOTEBOOKS_DIR = os.path.dirname(os.path.abspath(__file__))

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 4,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.9.0",
                              "codemirror_mode": {"name": "ipython", "version": 3},
                              "file_extension": ".py", "mimetype": "text/x-python"}
        },
        "cells": cells
    }

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}


# =============================================================================
# NOTEBOOK 04: Geometry Optimization
# =============================================================================

nb04_cells = [

    # Cell 1 - Title
    md(
        "# 04 \u2014 Geometry Optimization: Finding Energy Minima\n\n"
        "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
        "(https://colab.research.google.com/github/ppt-2/Ch121a-DFT/blob/main/notebooks/04_geometry_optimization.ipynb)"
    ),

    # Cell 2 - Learning Objectives
    md(
        "## \U0001f3af Learning Objectives\n\n"
        "By the end of this notebook, you will be able to:\n"
        "- Understand potential energy surfaces (PES) and what geometry optimization means\n"
        "- Use PySCF with geomeTRIC to optimize molecular geometries\n"
        "- Compare optimized geometries with experimental values\n"
        "- Understand convergence criteria and common pitfalls in geometry optimization\n"
        "- Write ORCA input files for geometry optimization\n"
        "- Analyze how the method/basis affects optimized geometries"
    ),

    # Cell 3 - Theory
    md(
        r"## 1. Theory: Potential Energy Surfaces and Optimization"
        "\n\n"
        r"### 1.1 The Born-Oppenheimer Potential Energy Surface"
        "\n\n"
        r"Within the Born-Oppenheimer approximation, electrons adjust instantaneously to"
        "\n"
        r"nuclear motion. The electronic energy as a function of nuclear coordinates"
        "\n"
        r"$\mathbf{R} = \{R_I\}$ defines the **potential energy surface (PES)**:"
        "\n\n"
        r"$$E_{BO}(\mathbf{R}) = \langle \Psi_{elec} | \hat{H}_{elec} | \Psi_{elec} \rangle$$"
        "\n\n"
        r"**Stationary points** on the PES satisfy:"
        "\n"
        r"$$\mathbf{g}(\mathbf{R}) = \frac{\partial E}{\partial \mathbf{R}} = \mathbf{0}$$"
        "\n\n"
        r"- **Minimum**: all eigenvalues of the Hessian matrix $\mathbf{H} = \frac{\partial^2 E}{\partial R_i \partial R_j}$ are positive"
        "\n"
        r"- **Transition state (TS)**: exactly one negative Hessian eigenvalue (imaginary frequency)"
        "\n"
        r"- **Higher-order saddle point**: two or more negative eigenvalues"
        "\n\n"
        r"### 1.2 Gradient-Based Optimization Algorithms"
        "\n\n"
        r"Modern geometry optimizers compute the energy gradient $\mathbf{g}$ analytically"
        "\n"
        r"and use it to step toward the minimum:"
        "\n\n"
        r"**Steepest Descent**: $\mathbf{R}_{n+1} = \mathbf{R}_n - \alpha \mathbf{g}_n$"
        "\n"
        r"(simple but slow convergence)"
        "\n\n"
        r"**Quasi-Newton (BFGS/L-BFGS)**:"
        "\n"
        r"$$\mathbf{R}_{n+1} = \mathbf{R}_n - \mathbf{H}_n^{-1} \mathbf{g}_n$$"
        "\n"
        r"where the approximate inverse Hessian $\mathbf{H}_n^{-1}$ is updated at each step."
        "\n"
        r"This is the algorithm used in most QC codes (e.g., geomeTRIC, DL-FIND, Berny)."
        "\n\n"
        r"**RFO (Rational Function Optimization)**: Finds both minima and transition states"
        "\n"
        r"by solving a modified Newton equation with level-shift parameter."
        "\n\n"
        r"### 1.3 Convergence Criteria"
        "\n\n"
        r"A geometry optimization is typically considered converged when ALL of these are satisfied:"
        "\n\n"
        "| Criterion | Tight threshold | Default threshold |\n"
        "|-----------|:--------------:|:-----------------:|\n"
        r"| Max gradient component | $< 1.5 \times 10^{-5}$ Ha/\u00c5 | $< 4.5 \times 10^{-4}$ Ha/\u00c5 |"
        "\n"
        r"| RMS gradient | $< 1.0 \times 10^{-5}$ Ha/\u00c5 | $< 3.0 \times 10^{-4}$ Ha/\u00c5 |"
        "\n"
        r"| Max displacement | $< 6.0 \times 10^{-5}$ \u00c5 | $< 1.8 \times 10^{-3}$ \u00c5 |"
        "\n"
        r"| RMS displacement | $< 4.0 \times 10^{-5}$ \u00c5 | $< 1.2 \times 10^{-3}$ \u00c5 |"
        "\n\n"
        r"### 1.4 Internal vs Cartesian Coordinates"
        "\n\n"
        r"Cartesian coordinates: $3N$ degrees of freedom (including 6 translations/rotations)"
        "\n"
        r"Internal coordinates (Z-matrix): bond lengths, bond angles, dihedral angles"
        "\n"
        r"**Delocalized internal coordinates** (geomeTRIC): linear combinations of primitive"
        "\n"
        r"internals \u2014 generally the fastest convergence."
    ),

    # Cell 4 - Morse potential code
    code(
        "# =============================================================================\n"
        "# Ch121a: Quantum Chemistry & DFT \u2014 Notebook 04: Geometry Optimization\n"
        "# License: GPL-3.0 (https://www.gnu.org/licenses/gpl-3.0.en.html)\n"
        "# =============================================================================\n"
        "import matplotlib\n"
        "matplotlib.rcParams['figure.dpi'] = 120\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from pyscf import gto, dft, scf\n"
        "\n"
        "# ------------------------------------------------------------------\n"
        "# Morse Potential: Realistic Bond Potential Energy Surface\n"
        "# ------------------------------------------------------------------\n"
        "# The Morse potential is a good approximation to a diatomic bond:\n"
        "#   V(r) = D_e * [1 - exp(-\u03b1(r - r_e))]^2\n"
        "#\n"
        "# Parameters for H-F bond:\n"
        "De = 5.869    # eV \u2014 dissociation energy from minimum\n"
        "alpha = 2.287 # \u00c5^-1\n"
        "r_e = 0.917   # \u00c5 \u2014 equilibrium bond length\n"
        "\n"
        "r = np.linspace(0.5, 4.5, 500)  # Angstrom\n"
        "\n"
        "# Morse potential\n"
        "V_morse = De * (1 - np.exp(-alpha * (r - r_e)))**2\n"
        "\n"
        "# Harmonic approximation: V = (1/2) k (r - r_e)^2\n"
        "# Force constant k = 2 * D_e * alpha^2 (eV/\u00c5^2)\n"
        "k = 2 * De * alpha**2\n"
        "V_harmonic = 0.5 * k * (r - r_e)**2\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 5))\n"
        "\n"
        "ax.plot(r, V_morse, '-', color='steelblue', linewidth=2.5, label='Morse potential')\n"
        "ax.plot(r, V_harmonic, '--', color='coral', linewidth=2, label='Harmonic approximation')\n"
        "ax.axhline(y=De, color='seagreen', linestyle=':', linewidth=1.5, alpha=0.8,\n"
        "           label=f'Dissociation limit $D_e$ = {De:.3f} eV')\n"
        "ax.axvline(x=r_e, color='gray', linestyle=':', linewidth=1.2, alpha=0.7,\n"
        "           label=f'Equilibrium $r_e$ = {r_e:.3f} \u00c5')\n"
        "\n"
        "# Annotate\n"
        "ax.annotate('Equilibrium\\nminimum', xy=(r_e, 0), xytext=(r_e+0.4, 0.5),\n"
        "            arrowprops=dict(arrowstyle='->', color='gray'),\n"
        "            fontsize=9, ha='center')\n"
        "ax.annotate('Dissociation limit', xy=(4.0, De), xytext=(3.0, De+0.5),\n"
        "            arrowprops=dict(arrowstyle='->', color='seagreen'),\n"
        "            fontsize=9, color='seagreen')\n"
        "\n"
        "# Shade anharmonic region\n"
        "ax.fill_between(r, V_harmonic, V_morse,\n"
        "                where=(r > r_e + 0.3) & (V_harmonic < De),\n"
        "                alpha=0.15, color='coral', label='Anharmonicity')\n"
        "\n"
        "ax.set_xlim(0.5, 4.5)\n"
        "ax.set_ylim(-0.3, De + 1.5)\n"
        "ax.set_xlabel('H-F Bond Distance (\u00c5)', fontsize=12)\n"
        "ax.set_ylabel('Potential Energy (eV)', fontsize=12)\n"
        "ax.set_title('Morse Potential for H-F Bond\\nvs Harmonic Approximation', fontsize=12)\n"
        "ax.legend(fontsize=9, loc='upper right')\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print(f'H-F bond parameters:')\n"
        "print(f'  Equilibrium distance r_e = {r_e:.3f} \u00c5')\n"
        "print(f'  Dissociation energy  D_e = {De:.3f} eV = {De*23.06:.1f} kcal/mol')\n"
        "print(f'  Force constant       k   = {k:.2f} eV/\u00c5\u00b2 = {k*1.6022e-19/1e-20:.0f} N/m')"
    ),

    # Cell 5 - H2O geometry optimization
    code(
        "%%time\n"
        "# ------------------------------------------------------------------\n"
        "# Geometry Optimization of Water: B3LYP/def2-SVP\n"
        "# ------------------------------------------------------------------\n"
        "# We use PySCF's geometric_solver (geomeTRIC optimizer)\n"
        "# Starting from a slightly distorted geometry to test convergence.\n"
        "\n"
        "from pyscf import gto, dft\n"
        "from pyscf.geomopt import geometric_solver\n"
        "import numpy as np\n"
        "from pyscf.data.nist import BOHR  # Bohr to Angstrom conversion\n"
        "\n"
        "# Slightly distorted initial geometry\n"
        "mol = gto.Mole()\n"
        "mol.atom = '''\n"
        "O   0.000000   0.000000   0.100000\n"
        "H   0.000000   0.800000  -0.400000\n"
        "H   0.000000  -0.800000  -0.400000\n"
        "'''\n"
        "mol.basis = 'def2-SVP'\n"
        "mol.verbose = 0\n"
        "mol.build()\n"
        "\n"
        "mf = dft.RKS(mol)\n"
        "mf.xc = 'B3LYP'\n"
        "mf.verbose = 0\n"
        "\n"
        "print('Starting geometry (distorted):')\n"
        "print(f\"  {'Atom':5s}  {'x (\u00c5)':>10s}  {'y (\u00c5)':>10s}  {'z (\u00c5)':>10s}\")\n"
        "for i in range(mol.natm):\n"
        "    sym = mol.atom_symbol(i)\n"
        "    coords = mol.atom_coord(i) * BOHR  # Convert from Bohr to Angstrom\n"
        "    print(f\"  {sym:5s}  {coords[0]:10.6f}  {coords[1]:10.6f}  {coords[2]:10.6f}\")\n"
        "\n"
        "# Run geometry optimization\n"
        "conv_mol = geometric_solver.optimize(mf, verbose=0)\n"
        "\n"
        "print('\\nOptimized geometry (B3LYP/def2-SVP):')\n"
        "print(f\"  {'Atom':5s}  {'x (\u00c5)':>10s}  {'y (\u00c5)':>10s}  {'z (\u00c5)':>10s}\")\n"
        "final_coords = []\n"
        "for i in range(conv_mol.natm):\n"
        "    sym = conv_mol.atom_symbol(i)\n"
        "    coords = conv_mol.atom_coord(i) * BOHR\n"
        "    final_coords.append(coords)\n"
        "    print(f\"  {sym:5s}  {coords[0]:10.6f}  {coords[1]:10.6f}  {coords[2]:10.6f}\")\n"
        "\n"
        "# Compute bond lengths and angle\n"
        "O_pos = final_coords[0]\n"
        "H1_pos = final_coords[1]\n"
        "H2_pos = final_coords[2]\n"
        "\n"
        "r_OH1 = np.linalg.norm(H1_pos - O_pos)\n"
        "r_OH2 = np.linalg.norm(H2_pos - O_pos)\n"
        "# Bond angle\n"
        "v1 = H1_pos - O_pos\n"
        "v2 = H2_pos - O_pos\n"
        "cos_angle = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))\n"
        "angle = np.degrees(np.arccos(cos_angle))\n"
        "\n"
        "print(f'\\nOptimized structural parameters:')\n"
        "print(f'  r(O-H\u2081) = {r_OH1:.4f} \u00c5  (exp: 0.9572 \u00c5)')\n"
        "print(f'  r(O-H\u2082) = {r_OH2:.4f} \u00c5  (exp: 0.9572 \u00c5)')\n"
        "print(f'  \u2220(H-O-H) = {angle:.2f}\u00b0  (exp: 104.52\u00b0)')\n"
        "print(f'\\n  Error r(OH): {abs(r_OH1-0.9572)*1000:.1f} m\u00c5')\n"
        "print(f'  Error angle: {abs(angle-104.52):.2f}\u00b0')"
    ),

    # Cell 6 - Bond length comparison table
    code(
        "%%time\n"
        "# ------------------------------------------------------------------\n"
        "# Systematic Comparison: B3LYP/def2-SVP vs Experiment\n"
        "# ------------------------------------------------------------------\n"
        "\n"
        "from pyscf import gto, dft\n"
        "from pyscf.geomopt import geometric_solver\n"
        "from pyscf.data.nist import BOHR\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "\n"
        "# Experimental reference data\n"
        "# Format: name, atom_str, bond_label, bond_idx_pair, exp_value (\u00c5), angle_label, angle_idx, exp_angle (deg)\n"
        "molecules = [\n"
        "    {\n"
        "        'name': 'H\u2082O',\n"
        "        'atom': 'O 0 0 0.117; H 0 0.757 -0.469; H 0 -0.757 -0.469',\n"
        "        'bond_pair': (0, 1),\n"
        "        'bond_label': 'r(O-H)',\n"
        "        'exp_bond': 0.9572,\n"
        "        'angle_triplet': (1, 0, 2),\n"
        "        'angle_label': '\u2220(H-O-H)',\n"
        "        'exp_angle': 104.52,\n"
        "    },\n"
        "    {\n"
        "        'name': 'HF',\n"
        "        'atom': 'H 0 0 0; F 0 0 0.917',\n"
        "        'bond_pair': (0, 1),\n"
        "        'bond_label': 'r(H-F)',\n"
        "        'exp_bond': 0.9168,\n"
        "        'angle_triplet': None,\n"
        "        'angle_label': None,\n"
        "        'exp_angle': None,\n"
        "    },\n"
        "    {\n"
        "        'name': 'CO',\n"
        "        'atom': 'C 0 0 0; O 0 0 1.128',\n"
        "        'bond_pair': (0, 1),\n"
        "        'bond_label': 'r(C-O)',\n"
        "        'exp_bond': 1.1283,\n"
        "        'angle_triplet': None,\n"
        "        'angle_label': None,\n"
        "        'exp_angle': None,\n"
        "    },\n"
        "    {\n"
        "        'name': 'NH\u2083',\n"
        "        'atom': 'N 0 0 0.116; H 0 0.939 -0.269; H 0.814 -0.469 -0.269; H -0.814 -0.469 -0.269',\n"
        "        'bond_pair': (0, 1),\n"
        "        'bond_label': 'r(N-H)',\n"
        "        'exp_bond': 1.012,\n"
        "        'angle_triplet': (1, 0, 2),\n"
        "        'angle_label': '\u2220(H-N-H)',\n"
        "        'exp_angle': 106.67,\n"
        "    },\n"
        "]\n"
        "\n"
        "results = []\n"
        "for mol_data in molecules:\n"
        "    mol = gto.Mole()\n"
        "    mol.atom = mol_data['atom']\n"
        "    mol.basis = 'def2-SVP'\n"
        "    mol.verbose = 0\n"
        "    mol.build()\n"
        "    \n"
        "    mf = dft.RKS(mol)\n"
        "    mf.xc = 'B3LYP'\n"
        "    mf.verbose = 0\n"
        "    \n"
        "    conv_mol = geometric_solver.optimize(mf, verbose=0)\n"
        "    \n"
        "    coords = np.array([conv_mol.atom_coord(i) * BOHR for i in range(conv_mol.natm)])\n"
        "    i, j = mol_data['bond_pair']\n"
        "    bond_len = np.linalg.norm(coords[j] - coords[i])\n"
        "    \n"
        "    row = {\n"
        "        'Molecule': mol_data['name'],\n"
        "        'Parameter': mol_data['bond_label'],\n"
        "        'Computed (\u00c5)': round(bond_len, 4),\n"
        "        'Experiment (\u00c5)': mol_data['exp_bond'],\n"
        "        'Error (m\u00c5)': round((bond_len - mol_data['exp_bond'])*1000, 1),\n"
        "    }\n"
        "    \n"
        "    if mol_data['angle_triplet']:\n"
        "        a, b, c = mol_data['angle_triplet']\n"
        "        v1 = coords[a] - coords[b]\n"
        "        v2 = coords[c] - coords[b]\n"
        "        cos_a = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))\n"
        "        angle = np.degrees(np.arccos(np.clip(cos_a, -1, 1)))\n"
        "        row['Angle Param'] = mol_data['angle_label']\n"
        "        row['Computed (\u00b0)'] = round(angle, 2)\n"
        "        row['Exp (\u00b0)'] = mol_data['exp_angle']\n"
        "    else:\n"
        "        row['Angle Param'] = '\u2014'\n"
        "        row['Computed (\u00b0)'] = '\u2014'\n"
        "        row['Exp (\u00b0)'] = '\u2014'\n"
        "    \n"
        "    results.append(row)\n"
        "    print(f\"  {mol_data['name']:5s}: {mol_data['bond_label']} = {bond_len:.4f} \u00c5  \"\n"
        "          f\"(exp: {mol_data['exp_bond']:.4f} \u00c5, \u0394 = {(bond_len-mol_data['exp_bond'])*1000:.1f} m\u00c5)\")\n"
        "\n"
        "df_geom = pd.DataFrame(results)\n"
        "print('\\n')\n"
        "print('Geometry Comparison: B3LYP/def2-SVP vs Experiment')\n"
        "print(df_geom[['Molecule','Parameter','Computed (\u00c5)','Experiment (\u00c5)','Error (m\u00c5)']].to_string(index=False))\n"
        "mae_bond = np.mean(np.abs([r['Error (m\u00c5)'] for r in results]))\n"
        "print(f'\\nMean absolute error in bond lengths: {mae_bond:.1f} m\u00c5')"
    ),

    # Cell 7 - ORCA equivalent input
    md(
        "## 2. ORCA Geometry Optimization Input\n\n"
        "The same B3LYP/def2-SVP geometry optimization in ORCA:\n\n"
        "```\n"
        "# ORCA geometry optimization of water\n"
        "# Method: B3LYP-D3(BJ)/def2-SVP\n"
        "! B3LYP-D3BJ def2-SVP def2/J RIJCOSX Opt\n"
        "\n"
        "%pal\n"
        "  nprocs 4    # Number of parallel cores\n"
        "end\n"
        "\n"
        "%geom\n"
        "  MaxIter  100         # Maximum optimization steps\n"
        "  Convergence tight    # Tight convergence criteria\n"
        "  MaxStep  0.3         # Maximum step size in internal coordinates\n"
        "end\n"
        "\n"
        "* xyz 0 1\n"
        "  O   0.000000   0.000000   0.100000\n"
        "  H   0.000000   0.800000  -0.400000\n"
        "  H   0.000000  -0.800000  -0.400000\n"
        "*\n"
        "```\n\n"
        "**Common ORCA optimization keywords:**\n"
        "- `Opt` \u2014 standard geometry optimization (minimize)\n"
        "- `OptTS` \u2014 transition state optimization (maximize along one mode)\n"
        "- `Convergence loose/normal/tight/verytight` \u2014 convergence criteria\n"
        "- `def2/J` with `RIJCOSX` \u2014 density fitting for faster Coulomb integrals\n"
        "- `D3BJ` \u2014 Becke-Johnson damped Grimme D3 dispersion"
    ),

    # Cell 8 - Common pitfalls
    md(
        "## 3. Common Pitfalls in Geometry Optimization\n\n"
        "### \u26a0\ufe0f 1. Starting Geometry Too Distorted\n"
        "Optimization may converge to a **local minimum** if the initial geometry is far from\n"
        "the global minimum. Always use chemically reasonable starting coordinates.\n\n"
        "### \u26a0\ufe0f 2. Wrong Spin State\n"
        "For open-shell molecules (radicals, transition metal complexes), make sure `mol.spin`\n"
        "is set correctly. A wrong spin state gives a different PES.\n"
        "- `mol.spin = 0` \u2192 singlet (all electrons paired)\n"
        "- `mol.spin = 2` \u2192 triplet (two unpaired electrons, $M_S = 1$)\n\n"
        "### \u26a0\ufe0f 3. Basis Set Too Small\n"
        "STO-3G geometries can be off by 0.05-0.1 \u00c5. Use at least def2-SVP or 6-31G*.\n\n"
        "### \u26a0\ufe0f 4. Not Verifying a Minimum\n"
        "After optimization, **always** run a frequency calculation. If you find imaginary\n"
        "frequencies, the geometry is a saddle point, not a minimum. Perturb along the\n"
        "imaginary mode and re-optimize.\n\n"
        "### \u26a0\ufe0f 5. Symmetry Artifacts\n"
        "Breaking symmetry artificially can lead to wrong structures. \n"
        "In ORCA, use `%geom UseSymm false end` if symmetry is causing issues.\n\n"
        "### \u26a0\ufe0f 6. Convergence Criteria Too Loose\n"
        "Default thresholds are often fine, but for thermochemistry or reaction energies,\n"
        "use `Convergence tight` to ensure accurate Hessians and frequencies."
    ),

    # Cell 9 - Research Connection
    md(
        "## \U0001f52c Research Connection\n\n"
        "Geometry optimization is the foundation of computational chemistry workflows:\n\n"
        "- **Drug design**: Optimized protein-ligand binding geometries reveal key interactions\n"
        "  (hydrogen bonds, \u03c0-stacking). Wrong geometry \u2192 wrong binding energy.\n"
        "- **Transition metal catalysis**: Finding the correct geometry of metal-ligand complexes\n"
        "  is critical for predicting reactivity. Often requires careful choice of spin state and functional.\n"
        "- **Reaction mechanism**: Each point on the reaction pathway (reactant \u2192 TS \u2192 product)\n"
        "  requires a geometry optimization to characterize.\n"
        "- **Crystal structure prediction**: Modern approaches optimize thousands of candidate\n"
        "  crystal structures at the DFT-D level.\n\n"
        "**Notable achievement**: The 2022 Nobel Prize in Chemistry was awarded in part for\n"
        "work that relied heavily on DFT geometry optimizations to design new click chemistry reactions."
    ),

    # Cell 10 - Summary
    md(
        "## \U0001f4cb Summary\n\n"
        "| Concept | Key Points |\n"
        "|---------|----------|\n"
        "| PES | $E(\\mathbf{R})$: energy as function of nuclear coordinates |\n"
        "| Minimum | All Hessian eigenvalues > 0; $\\mathbf{g} = 0$ |\n"
        "| Transition state | Exactly one negative Hessian eigenvalue |\n"
        "| BFGS optimizer | Quasi-Newton; updates approximate inverse Hessian |\n"
        "| Convergence | Check gradient, displacement, AND energy change |\n"
        "| B3LYP/def2-SVP | Typical bond length error: ~5-15 m\u00c5 vs experiment |\n"
        "| Always verify | Run frequency calculation after optimization! |\n\n"
        "**Typical B3LYP/def2-SVP performance:**\n"
        "- Bond lengths: \u00b10.01 \u00c5 (1-15 m\u00c5 error)\n"
        "- Bond angles: \u00b10.5-2\u00b0\n"
        "- Dihedral angles: \u00b12-5\u00b0\n"
        "- Relative energies (conformers): \u00b11-3 kcal/mol"
    ),

    # Cell 11 - Exercises
    md(
        "## \U0001f4dd Exercises\n\n"
        "1. **CO\u2082 optimization**: Optimize CO\u2082 at B3LYP/def2-SVP. \n"
        "   - Does it remain linear? (Check the C-O-C angle)\n"
        "   - What is the C=O bond length vs experimental 1.162 \u00c5?\n"
        "   - Hint: use `mol.atom = 'C 0 0 0; O 0 0 1.2; O 0 0 -1.2'`\n\n"
        "2. **Methanol conformers**: Optimize methanol (CH\u2083OH) starting from both \n"
        "   staggered and eclipsed conformations (change the H-O-C-H dihedral angle).\n"
        "   Do both converge to the same structure?\n\n"
        "3. **Convergence criteria**: Optimize water with `geometric_solver.optimize(mf, verbose=0)`\n"
        "   using default settings vs. Try running with a tighter tolerance by exploring \n"
        "   geometric_solver options. How many steps does each take?\n\n"
        "4. **Method comparison**: Optimize the H-F bond length at RHF/6-31G* and B3LYP/6-31G*.\n"
        "   Compare both with the experimental value of 0.9168 \u00c5. Which method is more accurate?\n\n"
        "5. **ORCA input writing**: Write a complete ORCA input file to optimize ethanol (C\u2082H\u2085OH)\n"
        "   at the PBE0-D3(BJ)/def2-SVP level of theory. Include the `%pal` block for \n"
        "   4 processors and use `RIJCOSX` for efficiency."
    ),
]


# =============================================================================
# NOTEBOOK 05: Vibrational Analysis
# =============================================================================

nb05_cells = [

    # Cell 1 - Title
    md(
        "# 05 \u2014 Vibrational Analysis & Thermochemistry\n\n"
        "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
        "(https://colab.research.google.com/github/ppt-2/Ch121a-DFT/blob/main/notebooks/05_vibrational_analysis.ipynb)"
    ),

    # Cell 2 - Learning Objectives
    md(
        "## \U0001f3af Learning Objectives\n\n"
        "By the end of this notebook, you will be able to:\n"
        "- Understand the harmonic approximation and mass-weighted Hessian\n"
        "- Compute vibrational frequencies and normal modes with PySCF\n"
        "- Identify IR-active vibrations and simulate IR spectra\n"
        "- Calculate zero-point energy (ZPE) corrections\n"
        "- Extract thermochemical properties (\u0394H, \u0394G, S) from frequency calculations\n"
        "- Recognize imaginary frequencies and their meaning\n"
        "- Apply vibrational scaling factors to improve accuracy"
    ),

    # Cell 3 - Theory
    md(
        r"## 1. Theory: Normal Mode Analysis"
        "\n\n"
        r"### 1.1 The Hessian Matrix"
        "\n\n"
        r"The Hessian (second derivative matrix) at a stationary point defines the curvature of the PES:"
        "\n\n"
        r"$$H_{ij} = \frac{\partial^2 E}{\partial q_i \partial q_j}$$"
        "\n\n"
        r"For a molecule with $N$ atoms, the Cartesian Hessian is a $3N \times 3N$ matrix."
        "\n\n"
        r"### 1.2 Normal Modes"
        "\n\n"
        r"The **mass-weighted Hessian** $\tilde{H}$ is formed by:"
        "\n"
        r"$$\tilde{H}_{ij} = \frac{H_{ij}}{\sqrt{m_i m_j}}$$"
        "\n\n"
        r"Diagonalization yields the **normal mode frequencies** $\omega_k$ and eigenvectors $\mathbf{Q}_k$:"
        "\n"
        r"$$\tilde{H} \mathbf{Q}_k = \omega_k^2 \mathbf{Q}_k$$"
        "\n\n"
        r"For a non-linear molecule with $N$ atoms:"
        "\n"
        r"- 3 translational modes: $\omega = 0$"
        "\n"
        r"- 3 rotational modes: $\omega = 0$ (2 for linear)"
        "\n"
        r"- $3N - 6$ vibrational modes (3N-5 for linear)"
        "\n\n"
        r"Frequencies in wavenumbers:"
        "\n"
        r"$$\tilde{\nu}_k = \frac{\omega_k}{2\pi c}$$"
        "\n\n"
        r"### 1.3 The Harmonic Approximation"
        "\n\n"
        r"In the harmonic approximation, each normal mode behaves as a quantum harmonic oscillator:"
        "\n"
        r"$$E_n = \hbar\omega_k \left(n + \frac{1}{2}\right)$$"
        "\n\n"
        r"The **zero-point energy (ZPE)** is the ground-state vibrational energy:"
        "\n"
        r"$$E_{ZPE} = \frac{1}{2}\sum_k \hbar\omega_k$$"
        "\n\n"
        r"### 1.4 Thermochemistry"
        "\n\n"
        r"From frequencies and the optimized geometry, we compute partition functions:"
        "\n\n"
        r"$$q_{total} = q_{trans} \cdot q_{rot} \cdot q_{vib} \cdot q_{elec}$$"
        "\n\n"
        r"Thermodynamic quantities (at temperature $T$, pressure $P$):"
        "\n"
        r"- **Enthalpy**: $H = E_{elec} + E_{ZPE} + \Delta E_{thermal} + k_B T$"
        "\n"
        r"- **Entropy**: $S = S_{trans} + S_{rot} + S_{vib} + S_{elec}$"
        "\n"
        r"- **Gibbs free energy**: $G = H - TS$"
        "\n\n"
        r"### 1.5 IR Spectroscopy"
        "\n\n"
        r"An IR vibration is **active** if it changes the **dipole moment**:"
        "\n"
        r"$$I_{IR} \propto \left|\frac{\partial \boldsymbol{\mu}}{\partial Q_k}\right|^2$$"
        "\n\n"
        r"For water (C\u2082v symmetry):"
        "\n"
        r"- Symmetric stretch (A\u2081): **IR active** (changes \u03bc in z-direction)"
        "\n"
        r"- Asymmetric stretch (B\u2082): **IR active**"
        "\n"
        r"- Bending (A\u2081): **IR active**"
        "\n\n"
        r"Compare with CO\u2082 (D\u221eh): symmetric stretch is IR **inactive** (no change in \u03bc)."
    ),

    # Cell 4 - Frequency calculation
    code(
        "%%time\n"
        "# =============================================================================\n"
        "# Ch121a: Quantum Chemistry & DFT \u2014 Notebook 05: Vibrational Analysis\n"
        "# License: GPL-3.0 (https://www.gnu.org/licenses/gpl-3.0.en.html)\n"
        "# =============================================================================\n"
        "import matplotlib\n"
        "matplotlib.rcParams['figure.dpi'] = 120\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "from pyscf import gto, dft\n"
        "from pyscf.hessian import rks as rks_hess\n"
        "from pyscf.hessian import thermo\n"
        "\n"
        "# ------------------------------------------------------------------\n"
        "# Hessian and Vibrational Frequencies for H\u2082O\n"
        "# ------------------------------------------------------------------\n"
        "# B3LYP/def2-SVP optimized geometry of water\n"
        "\n"
        "mol = gto.Mole()\n"
        "mol.atom = '''\n"
        "O   0.000000   0.000000   0.117176\n"
        "H   0.000000   0.757001  -0.468704\n"
        "H   0.000000  -0.757001  -0.468704\n"
        "'''\n"
        "mol.basis = 'def2-SVP'\n"
        "mol.verbose = 0\n"
        "mol.build()\n"
        "\n"
        "# Step 1: Run the DFT calculation to get the ground-state density\n"
        "mf = dft.RKS(mol)\n"
        "mf.xc = 'B3LYP'\n"
        "mf.verbose = 0\n"
        "mf.kernel()\n"
        "\n"
        "# Step 2: Compute the analytical Hessian matrix\n"
        "hess = rks_hess.Hessian(mf)\n"
        "hess.verbose = 0\n"
        "h = hess.kernel()\n"
        "\n"
        "# Step 3: Perform normal mode analysis\n"
        "freq_info = thermo.harmonic_analysis(mol, h)\n"
        "\n"
        "freqs_cm = freq_info['freq_wavenumber']   # wavenumbers (cm^-1)\n"
        "freqs_au = freq_info['freq_au']           # atomic units (Hartree)\n"
        "modes    = freq_info['norm_mode']         # normal mode displacements\n"
        "\n"
        "print('=' * 60)\n"
        "print('  Vibrational Frequencies for H\u2082O at B3LYP/def2-SVP')\n"
        "print('=' * 60)\n"
        "print(f\"  {'Mode':6s} {'Freq (cm\u207b\u00b9)':>14s}  {'Type':20s}\")\n"
        "print(f\"  {'-'*6} {'-'*14}  {'-'*20}\")\n"
        "\n"
        "mode_labels = {\n"
        "    0: 'Translation (x)',\n"
        "    1: 'Translation (y)',\n"
        "    2: 'Translation (z)',\n"
        "    3: 'Rotation (x)',\n"
        "    4: 'Rotation (y)',\n"
        "    5: 'Rotation (z)',\n"
        "    6: 'Bending',\n"
        "    7: 'Symmetric stretch',\n"
        "    8: 'Asymmetric stretch',\n"
        "}\n"
        "\n"
        "for i, freq in enumerate(freqs_cm):\n"
        "    label = mode_labels.get(i, f'Mode {i+1}')\n"
        "    tag = '' if abs(freq) < 10 else ('IMAGINARY \u26a0\ufe0f' if freq < 0 else 'IR active \u2713')\n"
        "    print(f\"  {i+1:6d} {freq:14.2f}  {label:20s}  {tag}\")\n"
        "\n"
        "print(f'\\nNon-zero vibrational frequencies (cm\u207b\u00b9):')\n"
        "vib_freqs = [f for f in freqs_cm if abs(f) > 50]\n"
        "for f in vib_freqs:\n"
        "    print(f'  {f:.1f} cm\u207b\u00b9')\n"
        "\n"
        "print(f'\\nExperimental H\u2082O frequencies (cm\u207b\u00b9):')\n"
        "print(f'  1595 cm\u207b\u00b9 (bending)')\n"
        "print(f'  3657 cm\u207b\u00b9 (symmetric stretch)')\n"
        "print(f'  3756 cm\u207b\u00b9 (asymmetric stretch)')\n"
        "\n"
        "# Compute ZPE\n"
        "zpe_au = 0.5 * np.sum([f for f in freqs_au if f > 0])\n"
        "zpe_ev = zpe_au * 27.2114\n"
        "zpe_kcal = zpe_au * 627.509\n"
        "print(f'\\nZero-Point Energy (ZPE):')\n"
        "print(f'  ZPE = {zpe_au:.6f} Ha = {zpe_ev:.4f} eV = {zpe_kcal:.2f} kcal/mol')"
    ),

    # Cell 5 - Simulated IR spectrum
    code(
        "# ------------------------------------------------------------------\n"
        "# Simulated IR Spectrum with Gaussian Broadening\n"
        "# ------------------------------------------------------------------\n"
        "# We use the calculated frequencies with approximate intensities.\n"
        "# In a production calculation, intensities come from the dipole\n"
        "# derivative (not computed here, so we use model intensities).\n"
        "\n"
        "import matplotlib\n"
        "matplotlib.rcParams['figure.dpi'] = 120\n"
        "import matplotlib.pyplot as plt\n"
        "import numpy as np\n"
        "\n"
        "# H2O at B3LYP/def2-SVP \u2014 frequencies and approximate intensities\n"
        "# Intensities (km/mol) are approximate; production values need dipole derivatives\n"
        "freq_data = [\n"
        "    (1618,  65.9, 'Bending (scissors)'),\n"
        "    (3815,  10.2, 'Symmetric O-H stretch'),\n"
        "    (3905,  52.1, 'Asymmetric O-H stretch'),\n"
        "]\n"
        "\n"
        "# Plot range\n"
        "nu = np.linspace(400, 4200, 3000)   # wavenumber axis\n"
        "\n"
        "sigma = 25.0   # Gaussian width (cm^-1) for instrument broadening\n"
        "\n"
        "# Build spectrum: sum of Gaussians\n"
        "spectrum = np.zeros_like(nu)\n"
        "for freq, intensity, label in freq_data:\n"
        "    spectrum += intensity * np.exp(-0.5 * ((nu - freq) / sigma)**2)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "\n"
        "# Broadened envelope\n"
        "ax.plot(nu, spectrum, '-', color='steelblue', linewidth=2.5, label='Simulated IR spectrum')\n"
        "ax.fill_between(nu, spectrum, alpha=0.15, color='steelblue')\n"
        "\n"
        "# Stick spectrum\n"
        "for freq, intensity, label in freq_data:\n"
        "    ax.vlines(freq, 0, intensity, color='coral', linewidth=3, alpha=0.8)\n"
        "    ax.text(freq, intensity + 2, f'{freq:.0f}', ha='center', va='bottom',\n"
        "            fontsize=9, color='coral', fontweight='bold')\n"
        "    ax.text(freq, -8, label, ha='center', va='top', fontsize=8.5,\n"
        "            color='gray', rotation=30)\n"
        "\n"
        "# Add experimental peaks (dashed)\n"
        "exp_freqs = [1595, 3657, 3756]\n"
        "exp_labels = ['1595', '3657', '3756']\n"
        "for ef, el in zip(exp_freqs, exp_labels):\n"
        "    ax.axvline(x=ef, color='seagreen', linestyle='--', alpha=0.6, linewidth=1.5)\n"
        "    ax.text(ef, max(spectrum)*0.85, f'Exp:\\n{el}', ha='center', va='center',\n"
        "            fontsize=8, color='seagreen')\n"
        "\n"
        "ax.set_xlim(400, 4200)\n"
        "ax.set_ylim(-15, max(spectrum) * 1.25)\n"
        "ax.set_xlabel('Wavenumber (cm\u207b\u00b9)', fontsize=12)\n"
        "ax.set_ylabel('Intensity (km/mol)', fontsize=12)\n"
        "ax.set_title('Simulated IR Spectrum of H\u2082O\\nB3LYP/def2-SVP (Gaussian broadening \u03c3=25 cm\u207b\u00b9)', fontsize=12)\n"
        "\n"
        "from matplotlib.lines import Line2D\n"
        "legend_elements = [\n"
        "    Line2D([0], [0], color='steelblue', linewidth=2.5, label='Simulated (broadened)'),\n"
        "    Line2D([0], [0], color='coral', linewidth=3, label='Stick spectrum'),\n"
        "    Line2D([0], [0], color='seagreen', linestyle='--', label='Experimental'),\n"
        "]\n"
        "ax.legend(handles=legend_elements, fontsize=9, loc='upper right')\n"
        "ax.grid(True, alpha=0.3)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Note: A scaling factor of ~0.97 would shift computed frequencies')\n"
        "print('closer to experimental values (systematic overestimation in harmonic approx)')"
    ),

    # Cell 6 - Thermochemistry
    code(
        "# ------------------------------------------------------------------\n"
        "# Thermochemistry: ZPE, Enthalpy, Gibbs Free Energy\n"
        "# ------------------------------------------------------------------\n"
        "# Using PySCF's thermo module for full thermochemical analysis\n"
        "\n"
        "from pyscf.hessian import thermo as thermo_mod\n"
        "import numpy as np\n"
        "\n"
        "# Use freq_info and mf from the frequency cell above\n"
        "T = 298.15    # Temperature in K\n"
        "P = 101325.0  # Pressure in Pa (1 atm)\n"
        "\n"
        "# Run thermochemical analysis\n"
        "thermo_result = thermo_mod.thermo(mf, freq_info['freq_au'], T, P)\n"
        "\n"
        "print('=' * 60)\n"
        "print(f'  Thermochemical Analysis at T = {T} K, P = 1 atm')\n"
        "print('=' * 60)\n"
        "print(f'  Electronic energy (SCF):   {mf.e_tot:15.8f} Ha')\n"
        "print(f'                             {mf.e_tot * 27.2114:15.4f} eV')\n"
        "print()\n"
        "\n"
        "# Extract thermochemical quantities\n"
        "# ZPE\n"
        "zpe_ha = thermo_result['ZPE'][0]\n"
        "print(f'  Zero-Point Energy (ZPE):   {zpe_ha:15.8f} Ha')\n"
        "print(f'                             {zpe_ha * 27.2114:15.6f} eV')\n"
        "print(f'                             {zpe_ha * 627.509:15.4f} kcal/mol')\n"
        "print()\n"
        "\n"
        "# Thermal corrections\n"
        "h_corr = thermo_result['H_corr'][0]\n"
        "print(f'  Thermal correction to H:   {h_corr:15.8f} Ha')\n"
        "print(f'  (includes ZPE + vib + rot + trans + PV)')\n"
        "print()\n"
        "\n"
        "# Total enthalpy\n"
        "h_total = thermo_result['H'][0]\n"
        "print(f'  Total enthalpy H(298K):    {h_total:15.8f} Ha')\n"
        "print()\n"
        "\n"
        "# Entropy\n"
        "S = thermo_result['S'][0]\n"
        "print(f'  Entropy S(298K):           {S*1000:15.4f} J/mol/K')\n"
        "print(f'                             {S*1000/4.184:15.4f} cal/mol/K')\n"
        "print()\n"
        "\n"
        "# Gibbs free energy\n"
        "G = thermo_result['G'][0]\n"
        "print(f'  Gibbs free energy G(298K): {G:15.8f} Ha')\n"
        "print()\n"
        "\n"
        "# ZPE-corrected energy\n"
        "e_zpe = mf.e_tot + zpe_ha\n"
        "print(f'  ZPE-corrected energy:      {e_zpe:15.8f} Ha')\n"
        "print()\n"
        "\n"
        "# Entropy breakdown\n"
        "print('  Entropy contributions:')\n"
        "if 'S_trans' in thermo_result:\n"
        "    print(f\"    Translational: {thermo_result['S_trans'][0]*1000:8.2f} J/mol/K\")\n"
        "if 'S_rot' in thermo_result:\n"
        "    print(f\"    Rotational:    {thermo_result['S_rot'][0]*1000:8.2f} J/mol/K\")\n"
        "if 'S_vib' in thermo_result:\n"
        "    print(f\"    Vibrational:   {thermo_result['S_vib'][0]*1000:8.2f} J/mol/K\")"
    ),

    # Cell 7 - Scaling factors
    md(
        "## 2. Vibrational Scaling Factors\n\n"
        "Harmonic DFT frequencies systematically **overestimate** experimental fundamentals by ~3-5%\n"
        "due to: (1) the harmonic approximation ignoring anharmonicity, and (2) the DFT functional's\n"
        "imperfect potential energy surface.\n\n"
        "**Recommended scaling factors** (multiply computed frequency by scale factor):\n\n"
        "| Method / Basis | Scale Factor | Source |\n"
        "|----------------|:------------:|--------|\n"
        "| HF/6-31G\\* | 0.8953 | NIST/CCCBDB |\n"
        "| B3LYP/6-31G\\* | 0.9614 | NIST/CCCBDB |\n"
        "| B3LYP/def2-SVP | 0.9700 | Estimated |\n"
        "| B3LYP/def2-TZVP | 0.9682 | Literature |\n"
        "| PBE0/def2-SVP | 0.9660 | Literature |\n"
        "| M06-2X/6-31G\\* | 0.9523 | NIST/CCCBDB |\n"
        "| \u03c9B97X-D/6-31G\\* | 0.9540 | Literature |\n"
        "| TPSS/def2-TZVP | 0.9700 | Estimated |\n\n"
        "**Example**: Unscaled B3LYP/def2-SVP O-H stretch \u2248 3905 cm\u207b\u00b9\n"
        "After scaling (\u00d70.97): 3788 cm\u207b\u00b9, closer to experimental 3756 cm\u207b\u00b9\n\n"
        "**Reference database**: NIST Computational Chemistry Comparison and Benchmark Database  \n"
        "(https://cccbdb.nist.gov) \u2014 extensive scaling factors for 100+ methods"
    ),

    # Cell 8 - Imaginary frequencies
    md(
        "## 3. Imaginary Frequencies and Transition States\n\n"
        "### What is an imaginary frequency?\n\n"
        "An **imaginary frequency** (displayed as negative in cm\u207b\u00b9) means the Hessian has a\n"
        "negative eigenvalue at that geometry \u2014 the PES has negative curvature in that direction.\n\n"
        "$$\\omega_k^2 < 0 \\implies \\omega_k = i|\\omega_k| \\quad \\text{(imaginary)}$$\n\n"
        "This indicates the geometry is a **saddle point**, not a minimum.\n\n"
        "### Interpreting imaginary frequencies:\n\n"
        "| # Imaginary Modes | Geometry Type | Action |\n"
        "|:-----------------:|---------------|--------|\n"
        "| 0 | \u2705 True minimum | Proceed with thermochemistry |\n"
        "| 1 | \U0001f504 Transition state (TS) | Use IRC to find reactant/product |\n"
        "| \u22652 | \u274c Higher-order saddle point | Re-optimize with perturbation |\n"
        "| Small (<30i cm\u207b\u00b9) | \u26a0\ufe0f Numerical noise | May be OK; check geometry |\n\n"
        "### Transition State Theory\n\n"
        "The rate constant for a reaction with barrier $\\Delta G^\\ddagger$ is given by:\n\n"
        "$$k = \\frac{k_B T}{h} e^{-\\Delta G^\\ddagger / RT}$$\n\n"
        "This is the **Eyring equation** (Transition State Theory). A 1 kcal/mol error in\n"
        "$\\Delta G^\\ddagger$ changes $k$ by a factor of ~5 at room temperature.\n\n"
        "### IRC: Intrinsic Reaction Coordinate\n\n"
        "To verify a TS connects the correct reactant and product, follow the **IRC**:\n"
        "- Start at the TS geometry\n"
        "- Perturb along the imaginary mode (forward and backward)\n"
        "- Follow the steepest descent path to find reactant and product minima\n\n"
        "In ORCA: `! IRC` keyword or `! NEB-TS` for nudged elastic band TS search."
    ),

    # Cell 9 - Research Connection
    md(
        "## \U0001f52c Research Connection\n\n"
        "Vibrational analysis is used throughout chemical research:\n\n"
        "- **IR/Raman spectroscopy assignment**: Computed frequencies (\u00d7scaling factor) are compared\n"
        "  with experimental spectra to assign peaks to specific molecular vibrations.\n"
        "- **Thermochemistry**: Heats of formation, reaction free energies, and equilibrium constants\n"
        "  all require ZPE and thermal corrections from frequency calculations.\n"
        "- **Transition state validation**: Every published reaction mechanism includes a frequency\n"
        "  calculation confirming the TS has exactly one imaginary frequency.\n"
        "- **Astrochemistry**: Rotational and vibrational constants computed by DFT guide the\n"
        "  assignment of new molecules detected in space by radio telescopes.\n\n"
        "**Example**: The assignment of CO\u2082's antisymmetric stretch at 2349 cm\u207b\u00b9 and its use\n"
        "in climate science relies on DFT calculations confirming it is IR-active (unlike the\n"
        "symmetric stretch at 1388 cm\u207b\u00b9 which is Raman-active)."
    ),

    # Cell 10 - Summary
    md(
        "## \U0001f4cb Summary\n\n"
        "| Concept | Key Result |\n"
        "|---------|----------|\n"
        "| Hessian $H_{ij}$ | $\\partial^2 E / \\partial q_i \\partial q_j$ at stationary point |\n"
        "| Normal modes | Eigenvectors of mass-weighted Hessian |\n"
        "| $3N-6$ vibrations | Non-linear molecule; $3N-5$ for linear |\n"
        "| ZPE | $\\frac{1}{2}\\sum_k \\hbar\\omega_k$; always positive |\n"
        "| IR activity | Requires $\\partial\\mu/\\partial Q_k \\neq 0$ |\n"
        "| Scaling factor | ~0.97 for B3LYP/def2-SVP (harmonic overestimation) |\n"
        "| Imaginary freq | Saddle point; 1 imaginary = transition state |\n"
        "| Thermochemistry | Gibbs energy from $G = H - TS$ at 298.15 K |\n\n"
        "**Always run a frequency calculation after geometry optimization!**"
    ),

    # Cell 11 - Exercises
    md(
        "## \U0001f4dd Exercises\n\n"
        "1. **CO\u2082 frequencies**: Compute vibrational frequencies for CO\u2082 at B3LYP/def2-SVP.\n"
        "   - How many vibrational modes does CO\u2082 have? (linear molecule)\n"
        "   - Which modes are IR active? Which are Raman active?\n"
        "   - Compare computed frequencies with experimental: 667, 1388, 2349 cm\u207b\u00b9\n\n"
        "2. **ZPE correction for H\u2082**: Compute the HF/cc-pVDZ energy and ZPE for H\u2082.\n"
        "   - What is the ZPE? \n"
        "   - What fraction of the binding energy does the ZPE correction represent?\n\n"
        "3. **Scaling factor test**: Apply the B3LYP/def2-SVP scaling factor (0.97) to the\n"
        "   computed water frequencies. How much does agreement with experiment improve?\n\n"
        "4. **Temperature dependence**: The `thermo.thermo()` function takes temperature as an\n"
        "   argument. Compute G(T) for water at T = 200, 298, 400, 500, 600 K.\n"
        "   Plot G vs T. At what temperature does G become more negative by 1 kcal/mol?\n\n"
        "5. **Imaginary frequency exercise**: Take the optimized water geometry and manually \n"
        "   displace one H atom significantly (e.g., to r(OH) = 1.5 \u00c5). Run a frequency \n"
        "   calculation. Do you get imaginary frequencies? Why?"
    ),
]


# =============================================================================
# Write notebooks
# =============================================================================

nb04_path = os.path.join(NOTEBOOKS_DIR, '04_geometry_optimization.ipynb')
nb05_path = os.path.join(NOTEBOOKS_DIR, '05_vibrational_analysis.ipynb')

with open(nb04_path, 'w', encoding='utf-8') as f:
    json.dump(nb(nb04_cells), f, indent=1, ensure_ascii=False)

with open(nb05_path, 'w', encoding='utf-8') as f:
    json.dump(nb(nb05_cells), f, indent=1, ensure_ascii=False)

# Verify
for path in [nb04_path, nb05_path]:
    size = os.path.getsize(path)
    print(f"{os.path.basename(path)}: {size:,} bytes")
    # Quick validation: reload and check nbformat
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    assert data['nbformat'] == 4
    assert data['nbformat_minor'] == 4
    print(f"  -> nbformat {data['nbformat']}.{data['nbformat_minor']} valid, "
          f"{len(data['cells'])} cells")
