import json, os

NOTEBOOKS_DIR = os.path.dirname(os.path.abspath(__file__))

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 4,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.9.0",
                              "codemirror_mode": {"name": "ipython", "version": 3},
                              "file_extension": ".py", "mimetype": "text/x-python"}
        },
        "cells": cells
    }

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}


cell1 = md(
    "# 06 — Molecular Properties: Dipoles, MOs, Fukui Functions & ESP\n"
    "\n"
    "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
    "(https://colab.research.google.com/github/ppt-2/Ch121a-DFT/blob/main/notebooks/06_molecular_properties.ipynb)"
)

cell2 = md(
    "## 🎯 Learning Objectives\n"
    "\n"
    "By the end of this notebook, you will be able to:\n"
    "- Compute and interpret molecular dipole moments\n"
    "- Analyze HOMO/LUMO energies and the HOMO-LUMO gap\n"
    "- Calculate chemical hardness η and chemical potential μ\n"
    "- Compute Fukui functions for reactivity prediction\n"
    "- Understand electrostatic potential (ESP) maps\n"
    "- Understand the concept of NMR chemical shielding (brief overview)\n"
    "- Connect DFT-computed properties to experimental observables"
)

cell3 = md(
    r"## 1. Theory: Molecular Properties from DFT" + "\n"
    "\n"
    r"### 1.1 Dipole Moment" + "\n"
    "\n"
    "The molecular dipole moment measures the asymmetry of the charge distribution:\n"
    "\n"
    r"$$\boldsymbol{\mu} = -\int \mathbf{r}\, n(\mathbf{r})\, d\mathbf{r} + \sum_I Z_I \mathbf{R}_I$$" + "\n"
    "\n"
    r"The magnitude in Debye: $\mu = |\boldsymbol{\mu}|$, where 1 D = 0.3934 a.u." + "\n"
    "\n"
    r"### 1.2 HOMO-LUMO Gap and Chemical Reactivity" + "\n"
    "\n"
    "From Koopmans' theorem extended to DFT (Janak's theorem):\n"
    "\n"
    r"$$IE \approx -\epsilon_{HOMO} \quad \text{(ionization energy)}$$" + "\n"
    r"$$EA \approx -\epsilon_{LUMO} \quad \text{(electron affinity, approximate)}$$" + "\n"
    "\n"
    "**Conceptual DFT** (Parr and Yang) defines:\n"
    r"- **Chemical potential**: $\mu_{chem} = \frac{\epsilon_{HOMO} + \epsilon_{LUMO}}{2} \approx -\frac{IE + EA}{2}$" + "\n"
    r"- **Chemical hardness**: $\eta = \frac{\epsilon_{LUMO} - \epsilon_{HOMO}}{2} \approx \frac{IE - EA}{2}$" + "\n"
    r"- **Electrophilicity index**: $\omega = \frac{\mu_{chem}^2}{2\eta}$" + "\n"
    "\n"
    "Soft molecules (small η) are more reactive; hard molecules are less reactive.\n"
    "\n"
    r"### 1.3 Fukui Functions" + "\n"
    "\n"
    "The **Fukui function** describes site-reactivity for electron addition/removal:\n"
    "\n"
    r"$$f^+(\mathbf{r}) = n_{N+1}(\mathbf{r}) - n_N(\mathbf{r}) \quad \text{(nucleophilic attack)}$$" + "\n"
    r"$$f^-(\mathbf{r}) = n_N(\mathbf{r}) - n_{N-1}(\mathbf{r}) \quad \text{(electrophilic attack)}$$" + "\n"
    r"$$f^0(\mathbf{r}) = \frac{f^+(\mathbf{r}) + f^-(\mathbf{r})}{2} \quad \text{(radical attack)}$$" + "\n"
    "\n"
    r"Using **condensed Fukui functions** from Mulliken charges $q_k$:" + "\n"
    r"$$f_k^+ = q_k(N+1) - q_k(N)$$" + "\n"
    r"$$f_k^- = q_k(N) - q_k(N-1)$$" + "\n"
    "\n"
    r"### 1.4 Electrostatic Potential (ESP)" + "\n"
    "\n"
    "The ESP measures the interaction energy between the molecular charge distribution\n"
    r"and a unit positive test charge at position $\mathbf{r}$:" + "\n"
    "\n"
    r"$$V(\mathbf{r}) = \sum_I \frac{Z_I}{|\mathbf{r}-\mathbf{R}_I|} - \int \frac{n(\mathbf{r}')}{|\mathbf{r}-\mathbf{r}'|} d\mathbf{r}'$$" + "\n"
    "\n"
    "- **Negative ESP** (red): electron-rich regions → sites for electrophilic attack\n"
    "- **Positive ESP** (blue): electron-poor regions → sites for nucleophilic attack\n"
    "- ESP mapped onto the molecular isodensity surface gives an **ESP map**"
)

cell4 = code(
    "%%time\n"
    "# =============================================================================\n"
    "# Ch121a: Quantum Chemistry & DFT — Notebook 06: Molecular Properties\n"
    "# License: GPL-3.0 (https://www.gnu.org/licenses/gpl-3.0.en.html)\n"
    "# =============================================================================\n"
    "import matplotlib\n"
    "matplotlib.rcParams['figure.dpi'] = 120\n"
    "import matplotlib.pyplot as plt\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "from pyscf import gto, dft, scf\n"
    "\n"
    "# ------------------------------------------------------------------\n"
    "# Dipole Moments: Computed vs Experimental\n"
    "# ------------------------------------------------------------------\n"
    "# Compute B3LYP/def2-SVP dipole moments for small polar molecules\n"
    "\n"
    "molecules_dip = {\n"
    "    'H\u2082O':  ('O 0 0 0.117; H 0 0.757 -0.469; H 0 -0.757 -0.469', 1.85),\n"
    "    'HF':   ('H 0 0 0; F 0 0 0.917',                               1.82),\n"
    "    'CO':   ('C 0 0 0; O 0 0 1.128',                               0.12),\n"
    "    'NH\u2083':  ('N 0 0 0.116; H 0 0.939 -0.269; H 0.814 -0.469 -0.269; H -0.814 -0.469 -0.269', 1.47),\n"
    "    'CO\u2082':  ('C 0 0 0; O 0 0 1.162; O 0 0 -1.162',                0.00),\n"
    "    'CH\u2084':  ('C 0 0 0; H 0.629 0.629 0.629; H -0.629 -0.629 0.629; H 0.629 -0.629 -0.629; H -0.629 0.629 -0.629', 0.00),\n"
    "}\n"
    "\n"
    "dip_results = []\n"
    "for name, (atom_str, exp_dip) in molecules_dip.items():\n"
    "    mol = gto.Mole()\n"
    "    mol.atom = atom_str\n"
    "    mol.basis = 'def2-SVP'\n"
    "    mol.verbose = 0\n"
    "    mol.build()\n"
    "    \n"
    "    mf = dft.RKS(mol)\n"
    "    mf.xc = 'B3LYP'\n"
    "    mf.verbose = 0\n"
    "    mf.kernel()\n"
    "    \n"
    "    dm = mf.make_rdm1()\n"
    "    dip_vec = mf.dip_moment(mol, dm, verbose=0)\n"
    "    dip_mag = np.linalg.norm(dip_vec)\n"
    "    \n"
    "    dip_results.append({\n"
    "        'Molecule': name,\n"
    "        'Computed (D)': round(dip_mag, 3),\n"
    "        'Experimental (D)': exp_dip,\n"
    "        'Error (D)': round(dip_mag - exp_dip, 3),\n"
    "    })\n"
    "    print(f\"  {name:5s}: \u03bc = {dip_mag:.3f} D (exp: {exp_dip:.2f} D)\")\n"
    "\n"
    "df_dip = pd.DataFrame(dip_results)\n"
    "print(\"\\n\")\n"
    "print(\"Dipole Moments: B3LYP/def2-SVP vs Experiment\")\n"
    "print(df_dip.to_string(index=False))\n"
    "mae_dip = np.mean(np.abs(df_dip['Error (D)']))\n"
    "print(f\"\\nMean Absolute Error: {mae_dip:.3f} D\")\n"
    "\n"
    "# Bar chart: computed vs experimental\n"
    "fig, ax = plt.subplots(figsize=(9, 4.5))\n"
    "x = np.arange(len(dip_results))\n"
    "width = 0.35\n"
    "names = [r['Molecule'] for r in dip_results]\n"
    "comp = [r['Computed (D)'] for r in dip_results]\n"
    "expt = [r['Experimental (D)'] for r in dip_results]\n"
    "\n"
    "bars1 = ax.bar(x - width/2, comp, width, color='steelblue', label='Computed (B3LYP/def2-SVP)',\n"
    "               edgecolor='white', linewidth=0.5)\n"
    "bars2 = ax.bar(x + width/2, expt, width, color='coral', label='Experimental',\n"
    "               edgecolor='white', linewidth=0.5, alpha=0.85)\n"
    "\n"
    "ax.set_xticks(x)\n"
    "ax.set_xticklabels(names, fontsize=11)\n"
    "ax.set_xlabel('Molecule', fontsize=12)\n"
    "ax.set_ylabel('Dipole Moment (Debye)', fontsize=12)\n"
    "ax.set_title('Dipole Moments: B3LYP/def2-SVP vs Experiment', fontsize=12)\n"
    "ax.legend(fontsize=10)\n"
    "ax.grid(True, alpha=0.3, axis='y')\n"
    "for bar, val in zip(bars1, comp):\n"
    "    if val > 0.05:\n"
    "        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,\n"
    "                f'{val:.2f}', ha='center', va='bottom', fontsize=8)\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

cell5 = code(
    "%%time\n"
    "# ------------------------------------------------------------------\n"
    "# HOMO/LUMO Analysis: Chemical Hardness and Chemical Potential\n"
    "# ------------------------------------------------------------------\n"
    "\n"
    "molecules_homo = {\n"
    "    'Ethylene\\n(C\u2082H\u2084)':  'C 0 0 0; C 0 0 1.34; H 0.924 0 -0.54; H -0.924 0 -0.54; H 0.924 0 1.88; H -0.924 0 1.88',\n"
    "    'Butadiene\\n(C\u2084H\u2086)':  'C 0 0 0; C 0 0 1.34; C 0 0.83 2.2; C 0 0.83 3.54; H 0.92 0 -0.54; H -0.92 0 -0.54; H 0 -0.93 1.88; H 0.92 1.76 1.65; H -0.92 1.76 1.65; H 0 -0.1 4.08',\n"
    "    'Benzene\\n(C\u2086H\u2086)':    'C 0 1.4 0; C 1.212 0.7 0; C 1.212 -0.7 0; C 0 -1.4 0; C -1.212 -0.7 0; C -1.212 0.7 0; H 0 2.48 0; H 2.147 1.24 0; H 2.147 -1.24 0; H 0 -2.48 0; H -2.147 -1.24 0; H -2.147 1.24 0',\n"
    "    'Naphthalene\\n(C\u2081\u2080H\u2088)': 'C 0.0 2.46 0; C 1.243 1.408 0; C 1.243 0.0 0; C 0.0 -0.705 0; C -1.243 0.0 0; C -1.243 1.408 0; C 1.243 -1.408 0; C 0.0 -2.113 0; C -1.243 -1.408 0; C 0.0 2.819 0; H 0.0 3.541 0; H 2.154 1.946 0; H 2.154 -1.946 0; H 0.0 -3.188 0; H -2.154 -1.946 0; H -2.154 1.946 0',\n"
    "}\n"
    "\n"
    "homo_results = []\n"
    "for name, atom_str in molecules_homo.items():\n"
    "    mol = gto.Mole()\n"
    "    mol.atom = atom_str\n"
    "    mol.basis = '6-31g*'\n"
    "    mol.verbose = 0\n"
    "    try:\n"
    "        mol.build()\n"
    "        mf = dft.RKS(mol)\n"
    "        mf.xc = 'B3LYP'\n"
    "        mf.verbose = 0\n"
    "        mf.kernel()\n"
    "        \n"
    "        mo_e = mf.mo_energy\n"
    "        mo_occ = mf.mo_occ\n"
    "        homo_idx = np.where(mo_occ > 0)[0][-1]\n"
    "        lumo_idx = homo_idx + 1\n"
    "        \n"
    "        homo_ev = mo_e[homo_idx] * 27.2114\n"
    "        lumo_ev = mo_e[lumo_idx] * 27.2114\n"
    "        gap = lumo_ev - homo_ev\n"
    "        eta = gap / 2.0\n"
    "        mu_chem = (homo_ev + lumo_ev) / 2.0\n"
    "        omega = mu_chem**2 / (2 * eta)\n"
    "        \n"
    "        homo_results.append({\n"
    "            'Molecule': name.replace('\\n', ' '),\n"
    "            'HOMO (eV)': round(homo_ev, 3),\n"
    "            'LUMO (eV)': round(lumo_ev, 3),\n"
    "            'Gap (eV)': round(gap, 3),\n"
    "            '\u03b7 (eV)': round(eta, 3),\n"
    "            '\u03bc_chem (eV)': round(mu_chem, 3),\n"
    "            '\u03c9 (eV)': round(abs(omega), 3),\n"
    "        })\n"
    "        print(f\"  {name.split(chr(10))[0]:12s}: HOMO={homo_ev:.2f} eV  LUMO={lumo_ev:.2f} eV  Gap={gap:.2f} eV  \u03b7={eta:.2f} eV\")\n"
    "    except Exception as e:\n"
    "        print(f\"  {name}: Error - {e}\")\n"
    "\n"
    "df_homo = pd.DataFrame(homo_results)\n"
    "print(\"\\n\")\n"
    "print(\"HOMO/LUMO Analysis: B3LYP/6-31G*\")\n"
    "print(df_homo.to_string(index=False))\n"
    "\n"
    "# Plot: HOMO-LUMO gap comparison\n"
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.5))\n"
    "\n"
    "mols = [r['Molecule'] for r in homo_results]\n"
    "homos = [r['HOMO (eV)'] for r in homo_results]\n"
    "lumos = [r['LUMO (eV)'] for r in homo_results]\n"
    "gaps = [r['Gap (eV)'] for r in homo_results]\n"
    "\n"
    "colors_pi = ['steelblue', 'seagreen', 'coral', 'mediumpurple']\n"
    "\n"
    "# Orbital energy diagram\n"
    "x_pos = np.arange(len(homo_results))\n"
    "for i, (mol_name, homo, lumo) in enumerate(zip(mols, homos, lumos)):\n"
    "    col = colors_pi[i % len(colors_pi)]\n"
    "    ax1.hlines(homo, i-0.3, i+0.3, colors=col, linewidth=5, label=f'HOMO' if i==0 else '')\n"
    "    ax1.hlines(lumo, i-0.3, i+0.3, colors=col, linewidth=5, linestyle='--', label=f'LUMO' if i==0 else '')\n"
    "    ax1.vlines(i, homo, lumo, colors=col, linewidth=1.5, alpha=0.4)\n"
    "\n"
    "ax1.set_xticks(x_pos)\n"
    "ax1.set_xticklabels([m.split(' ')[0] for m in mols], fontsize=9)\n"
    "ax1.set_ylabel('Orbital Energy (eV)', fontsize=12)\n"
    "ax1.set_title('HOMO/LUMO Energies\\nB3LYP/6-31G*', fontsize=12)\n"
    "ax1.grid(True, alpha=0.3, axis='y')\n"
    "ax1.axhline(y=0, color='black', linestyle=':', alpha=0.4)\n"
    "from matplotlib.lines import Line2D\n"
    "legend_elements = [Line2D([0],[0],color='gray',linewidth=5,label='HOMO (solid)'),\n"
    "                   Line2D([0],[0],color='gray',linewidth=5,linestyle='--',label='LUMO (dashed)')]\n"
    "ax1.legend(handles=legend_elements, fontsize=9)\n"
    "\n"
    "# Gap bar chart\n"
    "bars = ax2.bar(range(len(homo_results)), gaps, color=colors_pi[:len(homo_results)],\n"
    "               edgecolor='white', linewidth=0.5)\n"
    "ax2.set_xticks(range(len(homo_results)))\n"
    "ax2.set_xticklabels([m.split(' ')[0] for m in mols], fontsize=9)\n"
    "ax2.set_xlabel('Molecule', fontsize=12)\n"
    "ax2.set_ylabel('HOMO-LUMO Gap (eV)', fontsize=12)\n"
    "ax2.set_title('HOMO-LUMO Gaps\\n(smaller gap \u2192 more reactive)', fontsize=12)\n"
    "ax2.grid(True, alpha=0.3, axis='y')\n"
    "for bar, gap_val in zip(bars, gaps):\n"
    "    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,\n"
    "             f'{gap_val:.2f}', ha='center', va='bottom', fontsize=9)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

cell6 = code(
    "%%time\n"
    "# ------------------------------------------------------------------\n"
    "# Fukui Functions: Site-Specific Reactivity\n"
    "# ------------------------------------------------------------------\n"
    "# Condensed Fukui functions from Mulliken population analysis\n"
    "# for formaldehyde (H\u2082C=O)\n"
    "\n"
    "from pyscf import gto, dft\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib\n"
    "matplotlib.rcParams['figure.dpi'] = 120\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "def get_mulliken_charges(atom_str, n_electrons_adjust=0, basis='def2-SVP', xc='B3LYP'):\n"
    "    \"\"\"Return Mulliken charges for a molecule.\"\"\"\n"
    "    mol = gto.Mole()\n"
    "    mol.atom = atom_str\n"
    "    mol.basis = basis\n"
    "    mol.charge = n_electrons_adjust   # +1 = cation, -1 = anion\n"
    "    mol.spin = 0 if n_electrons_adjust == 0 else 1  # doublet for +1 or -1\n"
    "    mol.verbose = 0\n"
    "    mol.build()\n"
    "    \n"
    "    mf = dft.RKS(mol)\n"
    "    mf.xc = xc\n"
    "    mf.verbose = 0\n"
    "    mf.kernel()\n"
    "    \n"
    "    # Mulliken population analysis\n"
    "    dm = mf.make_rdm1()\n"
    "    mulliken = mf.mulliken_pop(mol, dm, verbose=0)\n"
    "    charges = mulliken[1]   # Mulliken charges (list per atom)\n"
    "    return charges, mol\n"
    "\n"
    "# Formaldehyde H\u2082C=O\n"
    "formaldehyde = '''\n"
    "C   0.000000   0.000000   0.000000\n"
    "O   0.000000   0.000000   1.208000\n"
    "H   0.935000   0.000000  -0.540000\n"
    "H  -0.935000   0.000000  -0.540000\n"
    "'''\n"
    "atom_labels = ['C', 'O', 'H\u2081', 'H\u2082']\n"
    "\n"
    "print(\"Computing Mulliken charges for formaldehyde (N, N-1, N+1)...\")\n"
    "\n"
    "# N electrons (neutral)\n"
    "q_N, mol_N = get_mulliken_charges(formaldehyde, 0)\n"
    "# N-1 electrons (cation, electrophilic attack)\n"
    "q_Nm1, mol_Nm1 = get_mulliken_charges(formaldehyde, +1)\n"
    "# N+1 electrons (anion, nucleophilic attack)\n"
    "q_Np1, mol_Np1 = get_mulliken_charges(formaldehyde, -1)\n"
    "\n"
    "q_N = np.array(q_N)\n"
    "q_Nm1 = np.array(q_Nm1)\n"
    "q_Np1 = np.array(q_Np1)\n"
    "\n"
    "# Condensed Fukui functions\n"
    "f_plus = q_Np1 - q_N    # f+ : nucleophilic attack (system gains electron)\n"
    "f_minus = q_N - q_Nm1   # f- : electrophilic attack (system loses electron)\n"
    "f_zero = (f_plus + f_minus) / 2.0  # f0 : radical attack\n"
    "\n"
    "print(f\"\\n  {'Atom':5s}  {'q(N)':>8s}  {'q(N-1)':>8s}  {'q(N+1)':>8s}  {'f+':>8s}  {'f-':>8s}  {'f0':>8s}\")\n"
    "print(f\"  {'-'*5}  {'-'*8}  {'-'*8}  {'-'*8}  {'-'*8}  {'-'*8}  {'-'*8}\")\n"
    "for i, (label, qn, qnm, qnp, fp, fm, fz) in enumerate(\n"
    "        zip(atom_labels, q_N, q_Nm1, q_Np1, f_plus, f_minus, f_zero)):\n"
    "    print(f\"  {label:5s}  {qn:8.4f}  {qnm:8.4f}  {qnp:8.4f}  {fp:8.4f}  {fm:8.4f}  {fz:8.4f}\")\n"
    "\n"
    "df_fukui = pd.DataFrame({\n"
    "    'Atom': atom_labels,\n"
    "    'q(N)': np.round(q_N, 4),\n"
    "    'f+ (nucl.)': np.round(f_plus, 4),\n"
    "    'f- (electr.)': np.round(f_minus, 4),\n"
    "    'f0 (radical)': np.round(f_zero, 4),\n"
    "})\n"
    "print(\"\\nFukui Functions Summary (B3LYP/def2-SVP):\")\n"
    "print(df_fukui.to_string(index=False))\n"
    "\n"
    "# Bar chart\n"
    "fig, axes = plt.subplots(1, 3, figsize=(12, 4))\n"
    "colors_at = ['steelblue', 'coral', 'seagreen', 'mediumpurple']\n"
    "\n"
    "for ax, (values, title, ylabel) in zip(axes, [\n"
    "    (f_plus, 'f\u207a (Nucleophilic Attack)\\nSite for electrophile?', 'Fukui f\u207a'),\n"
    "    (f_minus, 'f\u207b (Electrophilic Attack)\\nSite for nucleophile?', 'Fukui f\u207b'),\n"
    "    (f_zero, 'f\u2070 (Radical Attack)', 'Fukui f\u2070'),\n"
    "]):\n"
    "    bars = ax.bar(atom_labels, values, color=colors_at, edgecolor='white', linewidth=0.5)\n"
    "    ax.axhline(y=0, color='black', linewidth=0.8, linestyle='-')\n"
    "    ax.set_xlabel('Atom', fontsize=11)\n"
    "    ax.set_ylabel(ylabel, fontsize=10)\n"
    "    ax.set_title(title, fontsize=10)\n"
    "    ax.grid(True, alpha=0.3, axis='y')\n"
    "    for bar, val in zip(bars, values):\n"
    "        ax.text(bar.get_x() + bar.get_width()/2,\n"
    "                val + (0.005 if val >= 0 else -0.015),\n"
    "                f'{val:.3f}', ha='center', va='bottom' if val >= 0 else 'top',\n"
    "                fontsize=9)\n"
    "\n"
    "plt.suptitle('Condensed Fukui Functions for Formaldehyde (H\u2082C=O)\\nB3LYP/def2-SVP',\n"
    "             fontsize=12, fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "\n"
    "print(\"\\nInterpretation:\")\n"
    "print(\"  f+ > 0 at O: nucleophilic attack site (oxygen is electrophile-susceptible)\")\n"
    "print(\"  f- > 0 at C: electrophilic attack site (carbon is nucleophile-susceptible)\")\n"
    "print(\"  This is consistent with H\u2082C=O: O attacks electrophiles, C attacks nucleophiles\")"
)

cell7 = code(
    "# ------------------------------------------------------------------\n"
    "# Electrostatic Potential (ESP): Concept and Visualization\n"
    "# ------------------------------------------------------------------\n"
    "# While full ESP grid calculations require specialized tools (Multiwfn, ORCA),\n"
    "# we can visualize ESP conceptually using py3Dmol with a built-in surface.\n"
    "\n"
    "try:\n"
    "    import py3Dmol\n"
    "    \n"
    "    # Show water with a surface visualization\n"
    "    water_xyz = \"\"\"3\n"
    "Water molecule\n"
    "O   0.000000   0.000000   0.117176\n"
    "H   0.000000   0.757001  -0.468704\n"
    "H   0.000000  -0.757001  -0.468704\n"
    "\"\"\"\n"
    "    \n"
    "    view = py3Dmol.view(width=500, height=400)\n"
    "    view.addModel(water_xyz, 'xyz')\n"
    "    \n"
    "    # Stick model + VDW surface\n"
    "    view.setStyle({'stick': {'radius': 0.15}, 'sphere': {'scale': 0.25}})\n"
    "    view.addSurface(py3Dmol.VDW, {'opacity': 0.6,\n"
    "                                   'colorscheme': {'gradient': 'rwb',\n"
    "                                                   'min': -0.05, 'max': 0.05}})\n"
    "    view.setBackgroundColor('white')\n"
    "    view.zoomTo()\n"
    "    view.show()\n"
    "    print(\"ESP map displayed: red = electron-rich (negative), blue = electron-poor (positive)\")\n"
    "    \n"
    "except ImportError:\n"
    "    print(\"py3Dmol not installed. In a Colab/Jupyter environment, install with:\")\n"
    "    print(\"  pip install py3Dmol\")\n"
    "\n"
    "# Explain ESP calculation workflow\n"
    "print(\"\\n\" + \"=\" * 60)\n"
    "print(\"ESP Calculation Workflow:\")\n"
    "print(\"=\" * 60)\n"
    "print()\n"
    "print(\"1. Run DFT calculation to obtain density matrix\")\n"
    "print(\"2. Compute ESP on a grid of points surrounding the molecule:\")\n"
    "print(\"   V(r) = \u03a3_I Z_I/|r-R_I| - \u222b n(r')/|r-r'| dr'\")\n"
    "print()\n"
    "print(\"3. Map ESP onto molecular surface (typically \u03c1 = 0.001 a.u. isosurface)\")\n"
    "print()\n"
    "print(\"ESP maps can be generated with:\")\n"
    "print(\"  ORCA:      '! ESP' with %eprnmr or multiwfn post-processing\")\n"
    "print(\"  Gaussian:  'pop=mk' for Merz-Kollman ESP charges\")\n"
    "print(\"  Multiwfn:  Free tool for analyzing ESP from ORCA/Gaussian output\")\n"
    "print(\"  UCSF Chimera / VMD: Visualization of ESP-mapped surfaces\")\n"
    "print()\n"
    "print(\"ESP Applications:\")\n"
    "print(\"  \u2022 Identifying reactive sites (nucleophilic/electrophilic)\")\n"
    "print(\"  \u2022 Deriving partial charges for molecular mechanics (RESP charges)\")\n"
    "print(\"  \u2022 Understanding drug-receptor interactions\")\n"
    "print(\"  \u2022 Predicting regioselectivity in reactions\")"
)

cell8 = md(
    "## 2. NMR Chemical Shielding (Brief Overview)\n"
    "\n"
    "### Nuclear Magnetic Resonance (NMR) from DFT\n"
    "\n"
    "NMR chemical shifts arise from the electronic shielding of the nuclear magnetic moment\n"
    "by the surrounding electrons. DFT can compute the **isotropic chemical shielding tensor**:\n"
    "\n"
    r"$$\sigma_{iso} = \frac{1}{3}(\sigma_{xx} + \sigma_{yy} + \sigma_{zz})$$" + "\n"
    "\n"
    r"The chemical shift relative to a reference compound (TMS for ¹H/¹³C):" + "\n"
    r"$$\delta = \sigma_{ref} - \sigma_{iso}$$" + "\n"
    "\n"
    "### ORCA NMR Input\n"
    "\n"
    "```\n"
    "! B3LYP def2-TZVP NMR\n"
    "\n"
    "%eprnmr\n"
    "  Nuclei = all C { shift }    # 13C shielding\n"
    "  Nuclei = all H { shift }    # 1H shielding\n"
    "  GIAO = true                  # Gauge-including atomic orbitals (recommended)\n"
    "end\n"
    "\n"
    "* xyz 0 1\n"
    "  [molecule coordinates]\n"
    "*\n"
    "```\n"
    "\n"
    "### Key considerations for NMR calculations:\n"
    "\n"
    "| Aspect | Recommendation |\n"
    "|--------|---------------|\n"
    "| Functional | B3LYP, PBE0, or ωB97X-D |\n"
    "| Basis set | **def2-TZVP** minimum; pcSseg-2 or pcS-2 specialized NMR basis |\n"
    "| Gauge | Use **GIAO** (gauge-including atomic orbitals) always |\n"
    "| Reference | Calculate σ(TMS) at same level; δ = σ(TMS) - σ(molecule) |\n"
    "| Solvent | Include implicit solvation (CPCM) for solution-phase spectra |\n"
    "\n"
    "### Typical accuracy (¹H shifts):\n"
    "- B3LYP/def2-TZVP: ±0.2-0.5 ppm for most organic molecules\n"
    "- ωB97X-D/def2-TZVP: ±0.15-0.3 ppm\n"
    "\n"
    "**See Chapter 12** of the course notes for a full ORCA NMR tutorial with worked examples."
)

cell9 = md(
    "## 🔬 Research Connection\n"
    "\n"
    "Molecular properties from DFT are used throughout chemistry and biochemistry:\n"
    "\n"
    "- **Drug design**: Dipole moments and ESP maps guide pharmacophore design and predict\n"
    "  solubility, membrane permeability (log P), and protein binding modes.\n"
    "- **Organic synthesis**: Fukui functions predict regioselectivity of reactions\n"
    "  (e.g., which carbon is attacked in Michael additions, Friedel-Crafts alkylation).\n"
    "- **NMR structure determination**: ¹³C and ¹H chemical shifts computed at DFT level\n"
    "  are routinely used to distinguish between structural isomers and confirm synthesis products.\n"
    "- **Materials science**: HOMO/LUMO gaps predict optical band gaps for solar cell materials,\n"
    "  OLED emitters, and photocatalysts.\n"
    "\n"
    "**The HSAB principle** (Hard and Soft Acids and Bases, Pearson 1963) is quantified\n"
    "by chemical hardness η computed from DFT orbital energies — hard species prefer hard\n"
    "partners, soft species prefer soft partners in chemical reactions.\n"
    "\n"
    "**Notable application**: DFT-computed Fukui functions correctly predicted the\n"
    "C2-selective metalation of oxazoline heterocycles, later confirmed experimentally."
)

cell10 = md(
    "## 📋 Summary\n"
    "\n"
    "| Property | Formula | Physical Meaning |\n"
    "|----------|---------|------------------|\n"
    r"| Dipole moment | $\boldsymbol{\mu} = -\int \mathbf{r}\, n\, d\mathbf{r} + \sum Z_I \mathbf{R}_I$ | Charge asymmetry; polarity |" + "\n"
    r"| HOMO energy | $-\epsilon_{HOMO} \approx IE$ | Electron donation ability |" + "\n"
    r"| LUMO energy | $-\epsilon_{LUMO} \approx EA$ | Electron acceptance ability |" + "\n"
    r"| HOMO-LUMO gap | $\epsilon_{LUMO} - \epsilon_{HOMO}$ | Kinetic stability; color |" + "\n"
    r"| Chemical hardness | $\eta = (\epsilon_{LUMO} - \epsilon_{HOMO})/2$ | Resistance to electron flow |" + "\n"
    r"| Fukui f⁺ | $n_{N+1} - n_N$ | Nucleophilic attack site |" + "\n"
    r"| Fukui f⁻ | $n_N - n_{N-1}$ | Electrophilic attack site |" + "\n"
    r"| ESP | $V(\mathbf{r})$: nuclear - electronic potential | Reactivity map; partial charges |" + "\n"
    r"| NMR shielding | $\sigma_{iso}$ | Chemical shift prediction |" + "\n"
    "\n"
    "**Recommended methods:**\n"
    "- Dipole moments: B3LYP/def2-SVP (±0.1-0.2 D)\n"
    "- HOMO/LUMO: B3LYP or PBE0 / def2-SVP (qualitative trends)\n"
    "- Fukui functions: B3LYP/def2-SVP with Hirshfeld or CM5 charges (better than Mulliken)\n"
    "- NMR: B3LYP/def2-TZVP with GIAO (±0.3-0.5 ppm for ¹H)"
)

cell11 = md(
    "## 📝 Exercises\n"
    "\n"
    "1. **Dipole trend**: Compute dipole moments for the halogen fluorides: HF, ClF, BrF.\n"
    "   As you go down the periodic table, does the dipole moment increase or decrease? \n"
    "   Explain in terms of electronegativity and bond length.\n"
    "\n"
    "2. **HOMO-LUMO gap and color**: Compute B3LYP/6-31G* HOMO-LUMO gaps for:\n"
    "   - Anthracene (C₁₄H₁₀)\n"
    "   - Tetracene (C₁₈H₁₂)  \n"
    "   - Pentacene (C₂₂H₁₄)\n"
    "   Plot gap vs number of rings. These molecules are yellow, orange, and blue — \n"
    "   does the gap correlate with their absorption wavelengths?\n"
    "   (Hint: E = hc/λ; 1 eV ≈ 1240 nm)\n"
    "\n"
    "3. **Fukui for acrolein**: Compute Fukui functions for acrolein (CH₂=CH-CHO).\n"
    "   Acrolein undergoes 1,2- vs 1,4-addition. Which atom(s) have the largest f⁻?\n"
    "   Does this explain the preference for 1,4-addition?\n"
    "   Atom string: `C 0 0 0; C 0 0 1.34; C 0 0.83 2.2; O 0 0.83 3.4; H ...`\n"
    "\n"
    "4. **Hardness comparison**: Compute chemical hardness η for: \n"
    "   Na⁺, F⁻, BF₃, NF₃, H₂O, H₂S.\n"
    "   According to HSAB theory, which pairs would preferentially interact?\n"
    "\n"
    "5. **ESP charges**: Look up the ORCA `pop = chelpg` keyword for ESP-fitted charges.\n"
    "   Write an ORCA input for computing CHELPG charges on acrolein at B3LYP/def2-SVP.\n"
    "   How would these CHELPG charges differ from Mulliken charges?"
)

notebook = nb([cell1, cell2, cell3, cell4, cell5, cell6, cell7, cell8, cell9, cell10, cell11])

out_path = os.path.join(NOTEBOOKS_DIR, '06_molecular_properties.ipynb')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

size = os.path.getsize(out_path)
print(f"Created: {out_path}")
print(f"Size: {size:,} bytes")
