import json, os

NOTEBOOKS_DIR = os.path.dirname(os.path.abspath(__file__))

def nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 4,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.9.0",
                              "codemirror_mode": {"name": "ipython", "version": 3},
                              "file_extension": ".py", "mimetype": "text/x-python"}
        },
        "cells": cells
    }

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source}


# =============================================================================
# NOTEBOOK 00: 00_setup_and_tools.ipynb
# =============================================================================

nb00_cell1 = md(
    "# 00 — Setup & Tools: PySCF, ASE, py3Dmol, and Visualization\n"
    "\n"
    "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
    "(https://colab.research.google.com/github/ppt-2/Ch121a-DFT/blob/main/notebooks/00_setup_and_tools.ipynb)"
)

nb00_cell2 = md(
    "## 🎯 Learning Objectives\n"
    "\n"
    "By the end of this notebook, you will be able to:\n"
    "- Install and verify all required packages (PySCF, ASE, py3Dmol, cclib)\n"
    "- Run a basic Hartree-Fock calculation with PySCF on a small molecule\n"
    "- Manipulate molecular structures using ASE\n"
    "- Visualize molecules in 3D with py3Dmol\n"
    "- Parse quantum chemistry output files with cclib\n"
    "- Understand the overall computational chemistry workflow"
)

nb00_cell3 = code(
    "# =============================================================================\n"
    "# Ch121a: Quantum Chemistry & DFT — Notebook 00: Setup & Tools\n"
    "# License: GPL-3.0 (https://www.gnu.org/licenses/gpl-3.0.en.html)\n"
    "# =============================================================================\n"
    "# Install required packages (run this cell first, especially on Google Colab)\n"
    "import subprocess, sys\n"
    "\n"
    "packages = ['pyscf', 'ase', 'py3Dmol', 'nglview', 'cclib', 'matplotlib',\n"
    "            'numpy', 'pandas', 'scipy', 'seaborn', 'ipywidgets']\n"
    "\n"
    "for pkg in packages:\n"
    "    try:\n"
    "        __import__(pkg.replace('-','_').split('>=')[0])\n"
    "        print(f\"✓ {pkg} already installed\")\n"
    "    except ImportError:\n"
    "        print(f\"Installing {pkg}...\")\n"
    "        subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', pkg])\n"
    "        print(f\"✓ {pkg} installed\")"
)

nb00_cell4 = code(
    "# ------------------------------------------------------------------\n"
    "# Running a Hartree-Fock calculation with PySCF\n"
    "# ------------------------------------------------------------------\n"
    "# PySCF is a quantum chemistry package written entirely in Python.\n"
    "# It supports HF, DFT, MP2, CCSD, and many other methods.\n"
    "\n"
    "from pyscf import gto, scf\n"
    "import numpy as np\n"
    "\n"
    "# Step 1: Define the molecular structure\n"
    "mol = gto.Mole()\n"
    "mol.atom = '''\n"
    "O   0.000000   0.000000   0.117176\n"
    "H   0.000000   0.757001  -0.468704\n"
    "H   0.000000  -0.757001  -0.468704\n"
    "'''\n"
    "mol.basis = 'STO-3G'   # Minimal basis set — fast but not very accurate\n"
    "mol.charge = 0         # Neutral molecule\n"
    "mol.spin = 0           # Singlet (2S = 0, all electrons paired)\n"
    "mol.verbose = 0        # Suppress output (set to 3 or 4 for detailed output)\n"
    "mol.build()            # Build the molecular object (computes integrals)\n"
    "\n"
    "print(f\"Molecule: water (H₂O)\")\n"
    "print(f\"Number of atoms:             {mol.natm}\")\n"
    "print(f\"Number of electrons:         {mol.nelectron}\")\n"
    "print(f\"Number of basis functions:   {mol.nao_nr()}\")\n"
    "\n"
    "# Step 2: Set up and run a Restricted Hartree-Fock (RHF) calculation\n"
    "mf = scf.RHF(mol)\n"
    "mf.verbose = 0         # Suppress SCF convergence output\n"
    "energy = mf.kernel()   # Run the SCF procedure\n"
    "\n"
    "print(f\"\\nRHF/STO-3G Results:\")\n"
    "print(f\"  Total HF energy:   {energy:.8f} Hartree\")\n"
    "print(f\"  Total HF energy:   {energy * 27.2114:.4f} eV\")\n"
    "\n"
    "# Step 3: Analyze molecular orbital energies\n"
    "mo_energies = mf.mo_energy     # Orbital energies in Hartree\n"
    "mo_occ = mf.mo_occ             # Orbital occupancies (0 or 2 for RHF)\n"
    "\n"
    "homo_idx = np.where(mo_occ > 0)[0][-1]\n"
    "lumo_idx = homo_idx + 1\n"
    "\n"
    "print(f\"\\nMolecular Orbital Energies (eV):\")\n"
    "for i, (e, occ) in enumerate(zip(mo_energies, mo_occ)):\n"
    "    label = \"\"\n"
    "    if i == homo_idx:\n"
    "        label = \" ← HOMO\"\n"
    "    elif i == lumo_idx:\n"
    "        label = \" ← LUMO\"\n"
    "    status = \"occupied\" if occ > 0 else \"virtual\"\n"
    "    print(f\"  MO {i+1:2d} ({status:8s}): {e*27.2114:8.3f} eV{label}\")\n"
    "\n"
    "print(f\"\\nHOMO energy: {mo_energies[homo_idx]*27.2114:.3f} eV\")\n"
    "print(f\"LUMO energy: {mo_energies[lumo_idx]*27.2114:.3f} eV\")\n"
    "print(f\"HOMO-LUMO gap: {(mo_energies[lumo_idx]-mo_energies[homo_idx])*27.2114:.3f} eV\")"
)

nb00_cell5 = code(
    "# ------------------------------------------------------------------\n"
    "# Working with molecular structures using ASE\n"
    "# ------------------------------------------------------------------\n"
    "# ASE (Atomic Simulation Environment) provides tools for building,\n"
    "# manipulating, and analyzing molecular and periodic structures.\n"
    "\n"
    "from ase.build import molecule\n"
    "from ase.io import write\n"
    "import numpy as np\n"
    "\n"
    "# Build a water molecule from the G2 database\n"
    "water = molecule('H2O')\n"
    "\n"
    "print(\"ASE Atoms object for water (H₂O):\")\n"
    "print(f\"  Formula:          {water.get_chemical_formula()}\")\n"
    "print(f\"  Number of atoms:  {len(water)}\")\n"
    "print(f\"  Atomic numbers:   {water.get_atomic_numbers()}\")\n"
    "print(f\"  Chemical symbols: {water.get_chemical_symbols()}\")\n"
    "\n"
    "print(\"\\nAtomic positions (Angstrom):\")\n"
    "print(f\"  {'Symbol':6s}  {'x':>10s}  {'y':>10s}  {'z':>10s}\")\n"
    "print(f\"  {'-'*6}  {'-'*10}  {'-'*10}  {'-'*10}\")\n"
    "for atom in water:\n"
    "    print(f\"  {atom.symbol:6s}  {atom.x:10.6f}  {atom.y:10.6f}  {atom.z:10.6f}\")\n"
    "\n"
    "# Compute bond lengths\n"
    "from itertools import combinations\n"
    "print(\"\\nBond lengths:\")\n"
    "positions = water.get_positions()\n"
    "symbols = water.get_chemical_symbols()\n"
    "for (i, j) in combinations(range(len(water)), 2):\n"
    "    dist = np.linalg.norm(positions[i] - positions[j])\n"
    "    print(f\"  {symbols[i]}-{symbols[j]}: {dist:.4f} Å\")\n"
    "\n"
    "# ASE can build many common molecules\n"
    "print(\"\\nOther molecules available in ASE:\")\n"
    "for mol_name in ['NH3', 'CH4', 'CO2', 'C6H6', 'HF']:\n"
    "    m = molecule(mol_name)\n"
    "    print(f\"  {mol_name:6s}: {len(m)} atoms, formula = {m.get_chemical_formula()}\")"
)

nb00_cell6 = code(
    "# ------------------------------------------------------------------\n"
    "# 3D molecular visualization with py3Dmol\n"
    "# ------------------------------------------------------------------\n"
    "import py3Dmol\n"
    "\n"
    "# Water molecule in XYZ format\n"
    "water_xyz = \"\"\"3\n"
    "Water molecule (H2O) - B3LYP/def2-SVP optimized geometry\n"
    "O   0.000000   0.000000   0.117176\n"
    "H   0.000000   0.757001  -0.468704\n"
    "H   0.000000  -0.757001  -0.468704\n"
    "\"\"\"\n"
    "\n"
    "# Create a 3D viewer\n"
    "view = py3Dmol.view(width=500, height=400)\n"
    "\n"
    "# Add the molecule from XYZ format\n"
    "view.addModel(water_xyz, 'xyz')\n"
    "\n"
    "# Style the molecule: ball-and-stick representation\n"
    "view.setStyle({'stick': {'radius': 0.15}, 'sphere': {'scale': 0.3}})\n"
    "\n"
    "# Add labels for each atom\n"
    "view.addLabel('O', {'position': {'x': 0, 'y': 0, 'z': 0.117176},\n"
    "                    'fontSize': 14, 'fontColor': 'red',\n"
    "                    'backgroundColor': 'white', 'backgroundOpacity': 0.7})\n"
    "\n"
    "# Set background and zoom\n"
    "view.setBackgroundColor('white')\n"
    "view.zoomTo()\n"
    "view.show()\n"
    "print(\"3D visualization of water (H₂O)\")\n"
    "print(\"Tip: Click and drag to rotate, scroll to zoom.\")"
)

nb00_cell7 = code(
    "# ------------------------------------------------------------------\n"
    "# Parsing quantum chemistry output files with cclib\n"
    "# ------------------------------------------------------------------\n"
    "# cclib is a Python library for parsing output files from many\n"
    "# quantum chemistry programs: Gaussian, ORCA, NWChem, Molpro, etc.\n"
    "\n"
    "import os\n"
    "\n"
    "output_file = '../data/sample_outputs/water_opt_orca.out'\n"
    "\n"
    "try:\n"
    "    import cclib\n"
    "    if os.path.exists(output_file):\n"
    "        data = cclib.io.ccread(output_file)\n"
    "        print(\"Successfully parsed output file!\")\n"
    "        print(f\"  Program:            {data.metadata.get('package', 'unknown')}\")\n"
    "        print(f\"  Number of atoms:    {data.natom}\")\n"
    "        print(f\"  Number of basis:    {data.nbasis}\")\n"
    "        print(f\"  SCF energies (Ha):  {data.scfenergies[-1] / 27.2114:.8f}\")\n"
    "        print(f\"  Atoms:              {data.atomnos}\")\n"
    "    else:\n"
    "        print(f\"Note: Sample output file not found at '{output_file}'\")\n"
    "        print(\"In a real course, you would parse ORCA/Gaussian output files here.\")\n"
    "        print(\"\\ncclib supports parsing from: Gaussian, ORCA, NWChem, Molpro,\")\n"
    "        print(\"  Turbomole, Q-Chem, GAMESS, and many more programs.\")\n"
    "        print(\"\\nExample usage:\")\n"
    "        print(\"  import cclib\")\n"
    "        print(\"  data = cclib.io.ccread('your_calculation.out')\")\n"
    "        print(\"  print(data.scfenergies)  # SCF energies in eV\")\n"
    "        print(\"  print(data.atomcoords)   # Atomic coordinates in Angstrom\")\n"
    "        print(\"  print(data.vibfreqs)     # Vibrational frequencies in cm^-1\")\n"
    "except ImportError:\n"
    "    print(\"cclib not installed. Run: pip install cclib\")"
)

nb00_cell8 = code(
    "# ------------------------------------------------------------------\n"
    "# Computational Chemistry Workflow Diagram\n"
    "# ------------------------------------------------------------------\n"
    "import matplotlib\n"
    "matplotlib.rcParams['figure.dpi'] = 120\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.patches as mpatches\n"
    "from matplotlib.patches import FancyArrowPatch\n"
    "\n"
    "fig, ax = plt.subplots(figsize=(12, 4))\n"
    "ax.set_xlim(0, 12)\n"
    "ax.set_ylim(0, 4)\n"
    "ax.axis('off')\n"
    "\n"
    "# Workflow steps\n"
    "steps = [\n"
    "    ('Structure\\nBuilder', 1.0, 'steelblue',\n"
    "     ['ASE', 'Avogadro', 'Molden', 'GaussView']),\n"
    "    ('QC Engine', 3.5, 'coral',\n"
    "     ['PySCF', 'ORCA', 'Gaussian', 'NWChem']),\n"
    "    ('Analysis', 6.0, 'seagreen',\n"
    "     ['cclib', 'Multiwfn', 'AIMALL', 'Custom']),\n"
    "    ('Visualization', 8.5, 'mediumpurple',\n"
    "     ['py3Dmol', 'VMD', 'Avogadro', 'Pymol']),\n"
    "    ('Publication\\n& Report', 11.0, '#E67E22',\n"
    "     ['matplotlib', 'LaTeX', 'Origin', 'Excel']),\n"
    "]\n"
    "\n"
    "for (label, x, color, tools) in steps:\n"
    "    # Draw box\n"
    "    box = mpatches.FancyBboxPatch((x-0.8, 1.5), 1.6, 1.0,\n"
    "                                   boxstyle=\"round,pad=0.1\",\n"
    "                                   facecolor=color, edgecolor='white',\n"
    "                                   linewidth=2, alpha=0.9)\n"
    "    ax.add_patch(box)\n"
    "    ax.text(x, 2.05, label, ha='center', va='center',\n"
    "            fontsize=10, fontweight='bold', color='white')\n"
    "    # Tools below\n"
    "    for j, tool in enumerate(tools):\n"
    "        ax.text(x, 1.3 - j*0.22, tool, ha='center', va='center',\n"
    "                fontsize=7.5, color='gray', style='italic')\n"
    "\n"
    "# Arrows between boxes\n"
    "for i in range(len(steps)-1):\n"
    "    x1 = steps[i][1] + 0.8\n"
    "    x2 = steps[i+1][1] - 0.8\n"
    "    ax.annotate('', xy=(x2, 2.0), xytext=(x1, 2.0),\n"
    "                arrowprops=dict(arrowstyle='->', color='#555', lw=2))\n"
    "\n"
    "# Labels row headers\n"
    "ax.text(0.1, 2.05, '', ha='left', va='center', fontsize=9, color='#333')\n"
    "ax.text(0.1, 1.35, 'Tools:', ha='left', va='center', fontsize=8.5,\n"
    "        color='gray', fontweight='bold')\n"
    "\n"
    "ax.set_title('Computational Chemistry Workflow', fontsize=14,\n"
    "             fontweight='bold', pad=15)\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

nb00_cell9 = md(
    "## 🔬 Research Connection\n"
    "\n"
    "Modern quantum chemistry software like PySCF and ORCA is used in:\n"
    "\n"
    "- **Drug discovery**: Computing binding affinities, reaction mechanisms in enzyme active sites\n"
    "- **Materials science**: Predicting electronic properties of new solar cell materials\n"
    "- **Catalysis**: Understanding transition metal catalytic cycles (Nobel Prize 2022: click chemistry)\n"
    "- **Astrochemistry**: Modeling interstellar molecular spectra for telescope identification\n"
    "\n"
    "The Python ecosystem (PySCF + ASE + cclib + py3Dmol) enables fully reproducible,\n"
    "scriptable workflows — essential for modern computational science.\n"
    "\n"
    "**Key papers:**\n"
    "- Sun et al., *WIREs Comput. Mol. Sci.* **8**, e1340 (2018) — PySCF\n"
    "- Larsen et al., *J. Phys.: Condens. Matter* **29**, 273002 (2017) — ASE"
)

nb00_cell10 = md(
    "## 📋 Summary\n"
    "\n"
    "| Tool | Purpose | Key Function |\n"
    "|------|---------|-------------|\n"
    "| **PySCF** | Quantum chemistry calculations | HF, DFT, MP2, CCSD, ... |\n"
    "| **ASE** | Molecular structure manipulation | Build, read, write structures |\n"
    "| **py3Dmol** | 3D molecular visualization | Interactive browser-based viewer |\n"
    "| **cclib** | Parse QC output files | Extract energies, geometries, spectra |\n"
    "| **matplotlib** | Scientific plotting | Publication-quality figures |\n"
    "\n"
    "**Key concepts covered:**\n"
    "- Installing and verifying the computational chemistry Python stack\n"
    "- Running a complete HF/STO-3G calculation: molecule → SCF → orbital energies\n"
    "- The HOMO-LUMO gap as a measure of chemical reactivity\n"
    "- The 5-step computational chemistry workflow"
)

nb00_cell11 = md(
    "## 📝 Exercises\n"
    "\n"
    "1. **Basis set effect**: Modify the PySCF cell to use `6-31G*` instead of `STO-3G`. \n"
    "   How does the total energy and HOMO-LUMO gap change?\n"
    "\n"
    "2. **Different molecule**: Replace water with NH₃ (ammonia). \n"
    "   - Atom string: `N 0 0 0; H 0.94 0 0; H -0.47 0.82 0; H -0.47 -0.82 0`\n"
    "   - What is the HOMO energy? Estimate the first ionization energy (IE ≈ -ε_HOMO).\n"
    "   - Compare with the experimental IE of 10.07 eV.\n"
    "\n"
    "3. **ASE exploration**: Use `ase.build.molecule('C6H6')` to build benzene.\n"
    "   - How many C-C and C-H bonds does it have?\n"
    "   - What is the C-C bond length?\n"
    "\n"
    "4. **py3Dmol customization**: Modify the py3Dmol cell to display ammonia.\n"
    "   Try different styles: `'cartoon'`, `'surface'`, `'line'`.\n"
    "\n"
    "5. **cclib exploration**: If cclib is installed, use `cclib.io.ccread()` to parse\n"
    "   an ORCA or Gaussian output file of your choice. What attributes does the\n"
    "   resulting object have? (Hint: use `dir(data)`)"
)

notebook_00 = nb([
    nb00_cell1, nb00_cell2, nb00_cell3, nb00_cell4, nb00_cell5,
    nb00_cell6, nb00_cell7, nb00_cell8, nb00_cell9, nb00_cell10, nb00_cell11,
])


# =============================================================================
# NOTEBOOK 01: 01_molecular_structure_and_basis_sets.ipynb
# =============================================================================

nb01_cell1 = md(
    "# 01 — Molecular Structure & Basis Sets\n"
    "\n"
    "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
    "(https://colab.research.google.com/github/ppt-2/Ch121a-DFT/blob/main/notebooks/01_molecular_structure_and_basis_sets.ipynb)"
)

nb01_cell2 = md(
    "## 🎯 Learning Objectives\n"
    "\n"
    "By the end of this notebook, you will be able to:\n"
    "- Explain the difference between Slater-type (STO) and Gaussian-type (GTO) basis functions\n"
    "- Compare basis set families and understand accuracy/cost trade-offs\n"
    "- Perform basis set convergence studies for total energies\n"
    "- Understand contracted vs primitive basis functions\n"
    "- Understand effective core potentials (ECPs) and when to use them\n"
    "- Visualize atomic orbital radial probability distributions"
)

nb01_cell3 = md(
    "## 1. Theory: Basis Functions in Quantum Chemistry\n"
    "\n"
    "### 1.1 Slater-Type Orbitals (STOs)\n"
    "\n"
    "The exact hydrogen-like atomic orbitals are Slater-type orbitals (STOs):\n"
    "\n"
    r"$$\chi_{nlm}(r,\theta,\phi) = N r^{n-1} e^{-\zeta r} Y_l^m(\theta,\phi)$$"
    "\n"
    "\n"
    "where:\n"
    "- $N$ = normalization constant\n"
    "- $n$ = principal quantum number\n"
    r"- $\zeta$ (zeta) = orbital exponent controlling size"
    "\n"
    r"- $Y_l^m$ = spherical harmonic"
    "\n"
    "\n"
    "**Advantages:** Correct cusp at nucleus, correct exponential decay\n"
    "**Disadvantage:** Multi-center two-electron integrals are very expensive (no analytic formula)\n"
    "\n"
    "### 1.2 Gaussian-Type Orbitals (GTOs)\n"
    "\n"
    "In practice, we use Gaussian-type orbitals (GTOs):\n"
    "\n"
    r"$$g_{lmn}(\mathbf{r}; \alpha) = N x^l y^m z^n e^{-\alpha r^2}$$"
    "\n"
    "\n"
    r"where $\alpha$ is the Gaussian exponent and $l+m+n$ determines the angular momentum."
    "\n"
    "\n"
    "**Advantage:** Products of Gaussians are Gaussians → all integrals are analytic!\n"
    "**Disadvantage:** Incorrect behavior at nucleus (no cusp) and at long range (decays too fast)\n"
    "\n"
    "### 1.3 Contracted Basis Sets\n"
    "\n"
    "To capture STO-like behavior, we use **contracted** basis functions:\n"
    r"$$\chi_\mu = \sum_k d_{k\mu} g_k$$"
    "\n"
    "\n"
    r"A **contraction** combines multiple primitive Gaussians ($g_k$) with fixed coefficients ($d_{k\mu}$) to form a single basis function. For example, STO-3G uses 3 Gaussians to approximate each STO."
    "\n"
    "\n"
    "### 1.4 Basis Set Families\n"
    "\n"
    "| Family | Strategy | Example |\n"
    "|--------|----------|---------|\n"
    "| **Pople** | Add shells systematically | 6-31G, 6-31G\\*, 6-311G\\*\\* |\n"
    "| **Dunning** (cc-pVxZ) | Converges to CBS limit | cc-pVDZ, cc-pVTZ, cc-pVQZ |\n"
    "| **Ahlrichs** (def2) | Balanced accuracy/cost | def2-SVP, def2-TZVP, def2-QZVP |\n"
    "\n"
    "**Notation:**\n"
    "- **DZ** (double-ζ), **TZ** (triple-ζ), **QZ** (quadruple-ζ): number of basis functions per orbital\n"
    "- **\\*** or **P**: adds polarization functions (e.g., d functions on C, N, O)\n"
    "- **aug-**: adds diffuse functions (needed for anions, excited states, weak interactions)"
)

nb01_cell4 = code(
    "# =============================================================================\n"
    "# Ch121a: Quantum Chemistry & DFT — Notebook 01: Molecular Structure & Basis Sets\n"
    "# License: GPL-3.0 (https://www.gnu.org/licenses/gpl-3.0.en.html)\n"
    "# =============================================================================\n"
    "import matplotlib\n"
    "matplotlib.rcParams['figure.dpi'] = 120\n"
    "import matplotlib.pyplot as plt\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "from pyscf import gto, scf"
)

nb01_cell5 = code(
    "%%time\n"
    "# ------------------------------------------------------------------\n"
    "# Basis set convergence study for water (H2O)\n"
    "# ------------------------------------------------------------------\n"
    "# We compare HF energies across a range of basis sets to see\n"
    "# how the energy converges toward the complete basis set (CBS) limit.\n"
    "\n"
    "mol_template = \"\"\"\n"
    "O   0.000000   0.000000   0.117176\n"
    "H   0.000000   0.757001  -0.468704\n"
    "H   0.000000  -0.757001  -0.468704\n"
    "\"\"\"\n"
    "\n"
    "basis_sets = ['STO-3G', '3-21G', '6-31G*', 'cc-pVDZ', 'cc-pVTZ', 'def2-SVP', 'def2-TZVP']\n"
    "\n"
    "results = []\n"
    "for basis in basis_sets:\n"
    "    mol = gto.Mole()\n"
    "    mol.atom = mol_template\n"
    "    mol.basis = basis\n"
    "    mol.verbose = 0\n"
    "    mol.build()\n"
    "    mf = scf.RHF(mol)\n"
    "    mf.verbose = 0\n"
    "    e = mf.kernel()\n"
    "    n_bas = mol.nao_nr()\n"
    "    results.append({'Basis Set': basis, 'N_basis': n_bas,\n"
    "                    'E_HF (Ha)': round(e, 8), 'E_HF (eV)': round(e*27.2114, 5)})\n"
    "    print(f\"  {basis:12s}  N={n_bas:3d}  E = {e:.8f} Ha\")\n"
    "\n"
    "df = pd.DataFrame(results)\n"
    "print(\"\\n\")\n"
    "print(df.to_string(index=False))\n"
    "print(f\"\\ncc-pVTZ - STO-3G energy difference: {(results[4]['E_HF (Ha)']-results[0]['E_HF (Ha)'])*627.509:.2f} kcal/mol\")\n"
    "\n"
    "# Plot\n"
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))\n"
    "\n"
    "energies = [r['E_HF (Ha)'] for r in results]\n"
    "n_basis = [r['N_basis'] for r in results]\n"
    "labels = [r['Basis Set'] for r in results]\n"
    "\n"
    "# Panel 1: Energy vs basis set\n"
    "ax1.plot(range(len(basis_sets)), energies, 'o-', color='steelblue',\n"
    "         linewidth=2, markersize=8)\n"
    "ax1.axhline(y=energies[-1], color='coral', linestyle='--', alpha=0.7, label='def2-TZVP (reference)')\n"
    "ax1.set_xticks(range(len(basis_sets)))\n"
    "ax1.set_xticklabels(labels, rotation=30, ha='right', fontsize=9)\n"
    "ax1.set_xlabel('Basis Set')\n"
    "ax1.set_ylabel('HF Energy (Hartree)')\n"
    "ax1.set_title('Basis Set Convergence of HF Energy\\nfor H₂O')\n"
    "ax1.legend(fontsize=8)\n"
    "ax1.grid(True, alpha=0.3)\n"
    "\n"
    "# Panel 2: Number of basis functions vs basis set\n"
    "colors = ['steelblue' if 'STO' in b or '3-21' in b or '6-31G*' in b else\n"
    "          'seagreen' if 'cc-p' in b else 'coral' for b in labels]\n"
    "bars = ax2.bar(range(len(basis_sets)), n_basis, color=colors, edgecolor='white', linewidth=0.5)\n"
    "ax2.set_xticks(range(len(basis_sets)))\n"
    "ax2.set_xticklabels(labels, rotation=30, ha='right', fontsize=9)\n"
    "ax2.set_xlabel('Basis Set')\n"
    "ax2.set_ylabel('Number of Basis Functions')\n"
    "ax2.set_title('Basis Set Size for H₂O')\n"
    "ax2.grid(True, alpha=0.3, axis='y')\n"
    "for bar, n in zip(bars, n_basis):\n"
    "    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,\n"
    "             str(n), ha='center', va='bottom', fontsize=9)\n"
    "\n"
    "from matplotlib.patches import Patch\n"
    "legend_elements = [Patch(facecolor='steelblue', label='Pople'),\n"
    "                   Patch(facecolor='seagreen', label='Dunning (cc-pVxZ)'),\n"
    "                   Patch(facecolor='coral', label='Ahlrichs (def2)')]\n"
    "ax2.legend(handles=legend_elements, fontsize=8)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

nb01_cell6 = code(
    "# ------------------------------------------------------------------\n"
    "# Effective Core Potentials (ECPs)\n"
    "# ------------------------------------------------------------------\n"
    "# For heavy elements (3d, 4d, 5d transition metals, lanthanides),\n"
    "# the core electrons are chemically inert and their relativistic\n"
    "# effects can be captured via an ECP (pseudopotential).\n"
    "\n"
    "from pyscf import gto\n"
    "\n"
    "# Demonstrate ECP for Iron (Fe, Z=26)\n"
    "mol_Fe = gto.Mole()\n"
    "mol_Fe.atom = 'Fe 0 0 0'\n"
    "mol_Fe.basis = 'def2-SVP'\n"
    "mol_Fe.ecp = 'def2-SVP'     # Use the def2-SVP ECP for Fe\n"
    "mol_Fe.verbose = 0\n"
    "mol_Fe.build()\n"
    "\n"
    "print(\"=\" * 55)\n"
    "print(\"  Effective Core Potential (ECP) Demonstration: Fe\")\n"
    "print(\"=\" * 55)\n"
    "print(f\"  Element:                        Fe (Z = 26)\")\n"
    "print(f\"  ECP:                            def2-SVP\")\n"
    "print(f\"  Core electrons replaced by ECP: {mol_Fe.atom_nelec_core(0)}\")\n"
    "print(f\"  Valence electrons treated:      {mol_Fe.nelectron}\")\n"
    "print(f\"  Basis functions (valence only): {mol_Fe.nao_nr()}\")\n"
    "\n"
    "# Compare with all-electron def2-SVP (no ECP)\n"
    "mol_Fe_ae = gto.Mole()\n"
    "mol_Fe_ae.atom = 'Fe 0 0 0'\n"
    "mol_Fe_ae.basis = 'def2-SVP'\n"
    "mol_Fe_ae.verbose = 0\n"
    "mol_Fe_ae.build()\n"
    "print(f\"\\n  All-electron comparison:\")\n"
    "print(f\"  All electrons:                  {mol_Fe_ae.nelectron}\")\n"
    "print(f\"  Basis functions (all-electron): {mol_Fe_ae.nao_nr()}\")\n"
    "\n"
    "print(\"\\nWhen to use ECPs:\")\n"
    "print(\"  • Elements beyond Kr (Z > 36): relativistic effects important\")\n"
    "print(\"  • 3d metals: saves ~10 core electrons per atom\")\n"
    "print(\"  • 4d/5d metals: saves ~28/60 core electrons per atom\")\n"
    "print(\"  • Lanthanides/Actinides: ECP is essentially mandatory\")"
)

nb01_cell7 = code(
    "# ------------------------------------------------------------------\n"
    "# Radial Probability Distributions of Hydrogen-like Orbitals\n"
    "# ------------------------------------------------------------------\n"
    "# P(r) = r^2 |R_nl(r)|^2  (probability per unit radius)\n"
    "\n"
    "import matplotlib\n"
    "matplotlib.rcParams['figure.dpi'] = 120\n"
    "import matplotlib.pyplot as plt\n"
    "import numpy as np\n"
    "from scipy.special import factorial, genlaguerre\n"
    "\n"
    "def hydrogen_radial(n, l, r, Z=1):\n"
    "    \"\"\"Normalized radial wavefunction R_nl(r) for hydrogen-like atom.\"\"\"\n"
    "    rho = 2 * Z * r / n\n"
    "    # Normalization constant\n"
    "    norm = np.sqrt((2*Z/n)**3 * factorial(n-l-1) /\n"
    "                   (2*n * factorial(n+l)**3))\n"
    "    # Associated Laguerre polynomial\n"
    "    L = genlaguerre(n-l-1, 2*l+1)(rho)\n"
    "    return norm * np.exp(-rho/2) * rho**l * L\n"
    "\n"
    "r = np.linspace(0.001, 30, 2000)  # Bohr radii\n"
    "\n"
    "orbitals = [\n"
    "    (1, 0, '1s', 'steelblue',   '-'),\n"
    "    (2, 0, '2s', 'coral',        '-'),\n"
    "    (2, 1, '2p', 'seagreen',    '-'),\n"
    "    (3, 0, '3s', 'mediumpurple', '--'),\n"
    "    (3, 1, '3p', '#E67E22',      '--'),\n"
    "    (3, 2, '3d', '#E74C3C',      '--'),\n"
    "]\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
    "\n"
    "# Left plot: all orbitals together\n"
    "ax = axes[0]\n"
    "for n, l, label, color, ls in orbitals:\n"
    "    R = hydrogen_radial(n, l, r)\n"
    "    P = r**2 * R**2\n"
    "    ax.plot(r, P, label=f'${label}$', color=color, linestyle=ls, linewidth=2)\n"
    "ax.set_xlim(0, 25)\n"
    "ax.set_ylim(bottom=0)\n"
    "ax.set_xlabel('Radius $r$ (Bohr)', fontsize=12)\n"
    "ax.set_ylabel('Radial Probability $P(r) = r^2|R_{nl}|^2$', fontsize=11)\n"
    "ax.set_title('Hydrogen-like Radial Probability Distributions', fontsize=12)\n"
    "ax.legend(fontsize=11, ncol=2)\n"
    "ax.grid(True, alpha=0.3)\n"
    "\n"
    "# Right plot: n=1,2,3 s orbitals only (compare size)\n"
    "ax2 = axes[1]\n"
    "for n, l, label, color, ls in orbitals[:3]:\n"
    "    R = hydrogen_radial(n, l, r)\n"
    "    P = r**2 * R**2\n"
    "    # Mark the most probable radius\n"
    "    r_mp = r[np.argmax(P)]\n"
    "    ax2.plot(r, P, label=f'${label}$ ($r_{{mp}}$={r_mp:.1f} $a_0$)',\n"
    "             color=color, linewidth=2.5)\n"
    "    ax2.axvline(x=r_mp, color=color, linestyle=':', alpha=0.6)\n"
    "ax2.set_xlim(0, 15)\n"
    "ax2.set_ylim(bottom=0)\n"
    "ax2.set_xlabel('Radius $r$ (Bohr)', fontsize=12)\n"
    "ax2.set_ylabel('Radial Probability $P(r)$', fontsize=11)\n"
    "ax2.set_title('1s, 2s, 2p: Most Probable Radii', fontsize=12)\n"
    "ax2.legend(fontsize=10)\n"
    "ax2.grid(True, alpha=0.3)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.show()\n"
    "print(\"\\nNote: 1 Bohr = 0.529 Å\")\n"
    "print(\"Most probable radius for 1s: 1 Bohr (= Bohr radius a₀)\")"
)

nb01_cell8 = md(
    "## 2. Basis Set Reference Table\n"
    "\n"
    "| Basis Set | Family | # Fcns (H₂O) | Cost | Accuracy | Best Use Case |\n"
    "|-----------|--------|:------------:|:----:|:--------:|---------------|\n"
    "| STO-3G | Pople minimal | 7 | ★ | ★ | Quick tests, teaching |\n"
    "| 3-21G | Pople split-val | 13 | ★★ | ★★ | Qualitative trends |\n"
    "| 6-31G\\* | Pople + polariz | 19 | ★★ | ★★★ | Organic chemistry |\n"
    "| 6-311G\\*\\* | Pople triple-ζ | 30 | ★★★ | ★★★★ | Improved properties |\n"
    "| cc-pVDZ | Dunning DZ | 24 | ★★ | ★★★ | Correlated calculations |\n"
    "| cc-pVTZ | Dunning TZ | 58 | ★★★★ | ★★★★ | High accuracy |\n"
    "| aug-cc-pVDZ | Dunning aug-DZ | 41 | ★★★ | ★★★★ | Anions, polarizability |\n"
    "| def2-SVP | Ahlrichs SVP | 24 | ★★ | ★★★ | DFT, geometry opt |\n"
    "| def2-TZVP | Ahlrichs TZV | 58 | ★★★★ | ★★★★★ | Production DFT |\n"
    "\n"
    "**Rules of thumb:**\n"
    "- Start with **def2-SVP** for geometry optimizations\n"
    "- Use **def2-TZVP** for final energies and properties\n"
    "- Use **cc-pVTZ** or higher for correlated calculations (MP2, CCSD)\n"
    "- Add **aug-** prefix for anions, Rydberg states, polarizabilities, NMR\n"
    "- Use **ECPs** (def2-SVP/TZVP) for transition metals and heavy elements"
)

nb01_cell9 = md(
    "## 🔬 Research Connection\n"
    "\n"
    "Basis set choice is critical in published computational chemistry papers:\n"
    "\n"
    "- **Protein active sites**: def2-SVP is often used for QM/MM calculations on enzyme\n"
    "  active sites (50-200 atoms in the QM region) due to its cost/accuracy balance.\n"
    "- **CBS extrapolation**: High-accuracy thermochemistry (e.g., W4 theory, HEAT protocol)\n"
    "  uses cc-pVDZ through cc-pV5Z with extrapolation to the complete basis set limit.\n"
    "- **ORCA defaults**: ORCA uses def2-SVP as the default basis for geometry optimization\n"
    "  and def2-TZVP for single-point energies — matching our course workflow.\n"
    "\n"
    "**Key resource:** The EMSL Basis Set Exchange (https://www.basissetexchange.org/)\n"
    "provides basis sets in formats for all major QC programs."
)

nb01_cell10 = md(
    "## 📋 Summary\n"
    "\n"
    "**Key concepts:**\n"
    "- **STOs** are physically correct but computationally expensive; **GTOs** are analytically tractable and used in all modern codes\n"
    "- **Contracted** basis functions = fixed combinations of primitives; reduce computational cost\n"
    "- **Convergence hierarchy**: STO-3G < 3-21G < 6-31G\\* < cc-pVDZ < cc-pVTZ ← HF limit\n"
    "- **Polarization functions** (\\*) are essential for geometry and properties\n"
    "- **Diffuse functions** (aug-) needed for anions, excited states, and weak interactions\n"
    "- **ECPs** replace chemically inert core electrons in heavy elements with a potential\n"
    "\n"
    "**Practical recommendation for this course:**\n"
    "- Geometry optimization: **B3LYP/def2-SVP**\n"
    "- Single-point energies: **B3LYP/def2-TZVP** or **PBE0/def2-TZVP**\n"
    "- Heavy elements (3d metals): **def2-SVP** with ECP"
)

nb01_cell11 = md(
    "## 📝 Exercises\n"
    "\n"
    "1. **STO-3G vs cc-pVTZ**: Run HF/STO-3G and HF/cc-pVTZ on CO₂. \n"
    "   What is the C=O bond length predicted by each? Compare with experimental 1.162 Å.\n"
    "   (Hint: use `mol.atom = 'C 0 0 0; O 0 0 1.162; O 0 0 -1.162'`)\n"
    "\n"
    "2. **Convergence plot**: Extend the basis set convergence study to include \n"
    "   `aug-cc-pVDZ` and `aug-cc-pVTZ`. How do the energies compare to the cc- series?\n"
    "\n"
    "3. **ECP for copper**: Create a PySCF Mole object for Cu using def2-SVP with ECP.\n"
    "   How many core electrons are replaced? How does this compare to Fe?\n"
    "\n"
    "4. **Radial probability**: Modify the radial probability plot to show the 4s and 3d \n"
    "   orbitals. Why are these two orbitals similar in energy for transition metals?\n"
    "\n"
    "5. **Basis set superposition error (BSSE)**: Look up the counterpoise correction method.\n"
    "   Write pseudocode describing how you would estimate BSSE for the water dimer."
)

notebook_01 = nb([
    nb01_cell1, nb01_cell2, nb01_cell3, nb01_cell4, nb01_cell5,
    nb01_cell6, nb01_cell7, nb01_cell8, nb01_cell9, nb01_cell10, nb01_cell11,
])


# =============================================================================
# Write notebooks to disk
# =============================================================================

path_00 = os.path.join(NOTEBOOKS_DIR, "00_setup_and_tools.ipynb")
with open(path_00, "w", encoding="utf-8") as f:
    json.dump(notebook_00, f, indent=1, ensure_ascii=False)
print(f"✓ Written: {path_00}")

path_01 = os.path.join(NOTEBOOKS_DIR, "01_molecular_structure_and_basis_sets.ipynb")
with open(path_01, "w", encoding="utf-8") as f:
    json.dump(notebook_01, f, indent=1, ensure_ascii=False)
print(f"✓ Written: {path_01}")
